use truonghoc;
INSERT INTO DSTRUONG VALUE(N'79000767',N'Tiểu học THCS và THPT Quốc Văn Sài Gòn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'300 Hòa Bình');
INSERT INTO DSTRUONG VALUE(N'79000774',N'TH - THCS - THPT Chu Văn An',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'Số 7 Đường Số 1 Khu Phố 1');
INSERT INTO DSTRUONG VALUE(N'790007B9',N'Tiểu học THCS và THPT Mùa Xuân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'92 Nguyễn Hữu Cảnh phường 22 Quận Bình Thạnh');
INSERT INTO DSTRUONG VALUE(N'79000811',N'TH THCS THPT Tuệ Đức (2)',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'249/108 Tân Thới Nhất 17');
INSERT INTO DSTRUONG VALUE(N'79000813',N'Tiểu học THCS và THPT Ngô Thời Nhiệm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'65D Hồ Bá Phấn');
INSERT INTO DSTRUONG VALUE(N'79000818',N'TH - THCS - THPT VẠN HẠNH',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'781e Lê Hồng Phong P12 Q10');
INSERT INTO DSTRUONG VALUE(N'79000828',N'TH THCS và THPT Quốc Tế',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'305 Nguyễn Trọng Tuyển Phường 10 Quận Phú Nhuận');
INSERT INTO DSTRUONG VALUE(N'79000832',N'TH-THCS-THPT Thanh Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'192/12 Nguyễn Thái Bình');
INSERT INTO DSTRUONG VALUE(N'79000836',N'TH THCS và THPT Trương Vĩnh Ký',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79000848',N'Tiểu học THCS và THPT Việt Mỹ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79000852',N'TH THCS và THPT Nam Mỹ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79000858',N'Tiểu học THCS và THPT Tân Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'519 Kênh Tân Hóa');
INSERT INTO DSTRUONG VALUE(N'79000874',N'Tiểu học THCS và THPT Vinschool',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'Tòa CC3 khu đô thị Vinhomes Central Park 720A Điện Biên Phủ');
INSERT INTO DSTRUONG VALUE(N'79000888',N'Tiểu học THCS và THPT Lê Thánh Tông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79000C01',N'PTDL Hermann Gmeiner',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'697 Quang Trung');
INSERT INTO DSTRUONG VALUE(N'79000C03',N'Tiểu học THCS và THPT Việt Úc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'594 Ba Tháng Hai - phường 14 - Quận 10 - Tp. HCM');
INSERT INTO DSTRUONG VALUE(N'79000C04',N'THCS Song ngữ Quốc tế Horizon',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'6-6A-8 dường số 44');
INSERT INTO DSTRUONG VALUE(N'79000C05',N'Tiểu học THCS và THPT Quốc tế Canada',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'Số 86 Đường 23');
INSERT INTO DSTRUONG VALUE(N'79000C06',N'TiH - THCS - THPT QUỐC TẾ BẮC MỸ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'1 Đường 5A Kdc Trung Sơn');
INSERT INTO DSTRUONG VALUE(N'79000C07',N'Tiểu học THCS và THPT Thái Bình Dương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'125 Bạch Đằng');
INSERT INTO DSTRUONG VALUE(N'79000C09',N'TH THCS VÀ THPT Nguyễn Tri Phương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'61a Đường 30');
INSERT INTO DSTRUONG VALUE(N'79000C10',N'Tiểu học THCS và THPT Anh Quốc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79000C11',N'Tiểu học THCS và THPT Emasi Nam Long',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79000C12',N'Tiểu học THCS và THPT Mỹ Việt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'95 Phan Văn Hớn-Phường Tân Thới Nhất-Quận 12 - Thành Phố Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79000C13',N'Tiểu học THCS và THPT Emasi Vạn Phúc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79000C15',N'Tiểu học THCS và THPT Hoàng Gia',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79000C19',N'Tiểu học THCS và THPT Albert Einstein',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'Khu Dân Cư 13c đại lộ Nguyễn Văn Linh xã Phong Phú huyện Bình Chánh TP Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'7900QT01',N'Tiểu học THCS và THPT Quốc tế Khai Sáng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'7900QT02',N'Trường Quốc tế Việt Nam - Phần Lan',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'7900QT2',N'Trường Quốc tế Việt Nam - Phần Lan',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79760419',N'Tiểu học THCS  và THPT Quốc tế Á Châu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'Số 41/3-41/4 Bis Trần Nhật Duật');
INSERT INTO DSTRUONG VALUE(N'79767601',N'Tiểu học THCS và THPT Hòa Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'69 Trịnh Đình Thảo');
INSERT INTO DSTRUONG VALUE(N'79770601',N'TiH - THCS - THPT Tây Úc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'157 Lý Chính Thắng');
INSERT INTO DSTRUONG VALUE(N'79770702',N'Tiểu học THCS và THPT Úc Châu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79777418',N'Tiểu học THCS và THPT Ngôi Sao Nhỏ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'CBTH',N'10 Đường số 22 Phường Bình Trị Đông B Quận Bình Tân');
INSERT INTO DSTRUONG VALUE(N'79760401',N'TH Hòa Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'COLAP',N'PTHONG',N'CBTH',N'Số 01 Công Xã Paris');
INSERT INTO DSTRUONG VALUE(N'79760402',N'TH Kết Đoàn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'2B Lương Hữu Khánh');
INSERT INTO DSTRUONG VALUE(N'79760403',N'TH Đinh Tiên Hoàng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'67 Đinh Tiên Hoàng');
INSERT INTO DSTRUONG VALUE(N'79760404',N'TH Lê Ngọc Hân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'12 Sương Nguyệt Anh');
INSERT INTO DSTRUONG VALUE(N'79760406',N'TH Chương Dương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'296 Bis Bến Chương Dương');
INSERT INTO DSTRUONG VALUE(N'79760407',N'TH Trần Hưng Đạo',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'81 Trần Đình Xu');
INSERT INTO DSTRUONG VALUE(N'79760408',N'TH Khai Minh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'44 Phó Đức Chính');
INSERT INTO DSTRUONG VALUE(N'79760409',N'TH Nguyễn Thái Học',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'71 Trần Hưng Đạo');
INSERT INTO DSTRUONG VALUE(N'79760410',N'TH Nguyễn Thái Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'105 Nguyễn Thái Bình');
INSERT INTO DSTRUONG VALUE(N'79760411',N'TH Trần Khánh Dư',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'53/61 Trần Khánh Dư');
INSERT INTO DSTRUONG VALUE(N'79760412',N'TH Trần Quang Khải',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'68/29B Trần Quang Khải');
INSERT INTO DSTRUONG VALUE(N'79760413',N'TH Phan Văn Trị',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'43 Phạm Viết Chánh');
INSERT INTO DSTRUONG VALUE(N'79760414',N'Tiểu học Nguyễn Bỉnh Khiêm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'2 Bis Nguyễn Bỉnh Khiêm phường Bến Nghé quận Bình Thạnh');
INSERT INTO DSTRUONG VALUE(N'79760415',N'Tiểu học Đuốc Sống',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'2 Đinh Công Tráng');
INSERT INTO DSTRUONG VALUE(N'79760416',N'TH Nguyễn Huệ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'93-95A Lê Thị Riêng');
INSERT INTO DSTRUONG VALUE(N'79760418',N'TH Lương Thế Vinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q01',N'COLAP',N'PTHONG',N'CBTH',N'116 Cô Giang');
INSERT INTO DSTRUONG VALUE(N'70123015',N'Tiểu học Nam Việt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79761401',N'TH Phạm Văn Chiêu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'2683/1A Kp1');
INSERT INTO DSTRUONG VALUE(N'79761402',N'TH Quang Trung',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'17b Kp4');
INSERT INTO DSTRUONG VALUE(N'79761403',N'TH Hà Huy Giáp',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'84/1 Khu Phố 1');
INSERT INTO DSTRUONG VALUE(N'79761404',N'TH Nguyễn Du',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'A36bis Kp1');
INSERT INTO DSTRUONG VALUE(N'79761405',N'TH Nguyễn Khuyến',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'30/A1 Kp1A');
INSERT INTO DSTRUONG VALUE(N'79761406',N'TH Trần Văn Ơn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'78/4a bis-KP7Trường Chinh');
INSERT INTO DSTRUONG VALUE(N'79761407',N'TH Quới Xuân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'219/4 Kp5');
INSERT INTO DSTRUONG VALUE(N'79761408',N'TH Nguyễn Văn Thệ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'326 Hà Huy Giáp Kp3');
INSERT INTO DSTRUONG VALUE(N'79761409',N'TH Nguyễn Thị Minh Khai',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'11at1 Khu Phố 1 Phường Tân Thới Nhất Quận 12');
INSERT INTO DSTRUONG VALUE(N'79761410',N'TH Thuận Kiều',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'62/14b Kp6');
INSERT INTO DSTRUONG VALUE(N'79761411',N'TH Lê Văn Thọ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'225 Kp4 đường Nguyễn Thị Kiểu P.Tân Thới Hiệp Quận 12 TP.HCM');
INSERT INTO DSTRUONG VALUE(N'79761412',N'TH Trần Quang Cơ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'Kp3');
INSERT INTO DSTRUONG VALUE(N'79761413',N'TH Hồ Văn Thanh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'24/1.kp6');
INSERT INTO DSTRUONG VALUE(N'79761414',N'TH Kim Đồng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'Số 1 Đường Số 2');
INSERT INTO DSTRUONG VALUE(N'79761415',N'Tiểu học Nguyễn Trãi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'170/4A Kp1');
INSERT INTO DSTRUONG VALUE(N'79761416',N'TH Võ Văn Tần',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'Khu phố 5');
INSERT INTO DSTRUONG VALUE(N'79761418',N'TH Trương Định',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'Khu Phố 4');
INSERT INTO DSTRUONG VALUE(N'79761419',N'TH Thần Đồng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'TTHUC',N'PTHONG',N'CBTH',N'229/1/1 A');
INSERT INTO DSTRUONG VALUE(N'79761420',N'Tiểu học Nguyễn Thị Định',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'TTN01  -  Khu Phố 3');
INSERT INTO DSTRUONG VALUE(N'79761421',N'TH Nguyễn Thái Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'Số 21 Đường HT 11 Kp3 Phường Hiệp Thành Quận 12');
INSERT INTO DSTRUONG VALUE(N'79761422',N'Tiểu học Lý Tự Trọng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'112/30 khu phố 5');
INSERT INTO DSTRUONG VALUE(N'79761423',N'TH Võ Thị Sáu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',N'Khu phố 3');
INSERT INTO DSTRUONG VALUE(N'79761424',N'TH Võ Thị Thừa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q12',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79762401',N'TH Nguyễn Trung Trực',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'962 Kha Vạn Cân');
INSERT INTO DSTRUONG VALUE(N'79762402',N'TH Lương Thế Vinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'1 Dân Chủ- KP2- phường Bình Thọ- Quận Thủ Đức- TP Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79762404',N'TH Bình Triệu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'144/12 Quốc Lộ 13 KP2');
INSERT INTO DSTRUONG VALUE(N'79762405',N'TH Đặng Thị Rành',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'137 Quốc Lộ 13 cũ  Kp3');
INSERT INTO DSTRUONG VALUE(N'79762406',N'TH Hiệp Bình Phước',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'630 Quốc Lộ 13');
INSERT INTO DSTRUONG VALUE(N'79762407',N'TH Thái Văn Lung 1',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'93/6 Tam Châu Kp5');
INSERT INTO DSTRUONG VALUE(N'79762408',N'TH Tam Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'71 đường 10 Khu phố 3');
INSERT INTO DSTRUONG VALUE(N'79762409',N'TH Trần Văn Vân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'15 đường 11 Kp4');
INSERT INTO DSTRUONG VALUE(N'79762410',N'TH Bình Chiểu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'902 tỉnh lộ 43 kp1 p.Bình Chiểu');
INSERT INTO DSTRUONG VALUE(N'79762411',N'TH Xuân Hiệp',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'Linh Xuân');
INSERT INTO DSTRUONG VALUE(N'79762412',N'Tiểu học Hoàng Diệu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'33 Lê Văn Chí Kp3');
INSERT INTO DSTRUONG VALUE(N'79762413',N'TH Nguyễn Văn Triết',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'57 Hoàng Diệu Kp2');
INSERT INTO DSTRUONG VALUE(N'79762414',N'Tiểu học Linh Tây',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'16/5 Kp2');
INSERT INTO DSTRUONG VALUE(N'79762415',N'TH Bình Quới',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'18/18 Đường 22 Kp4');
INSERT INTO DSTRUONG VALUE(N'79762416',N'TH Đặng Văn Bất',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'30/6 Đường 35 Kp2');
INSERT INTO DSTRUONG VALUE(N'79762417',N'Tiểu Học Linh Đông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'170 Tô Ngọc Vân');
INSERT INTO DSTRUONG VALUE(N'79762418',N'TH Nguyễn Văn Banh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'7/9a Kp5');
INSERT INTO DSTRUONG VALUE(N'79762419',N'TH Hiệp Bình Chánh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'29 đường1 Khu phố 5');
INSERT INTO DSTRUONG VALUE(N'79762420',N'TH Từ Đức',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'6 Đường Đoàn Kết Kp3');
INSERT INTO DSTRUONG VALUE(N'79762421',N'TH Trương Văn Hải',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'76  Phú Châu');
INSERT INTO DSTRUONG VALUE(N'79762422',N'TH Nguyễn Văn Lịch',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'Số 66 Đường 6 Kp3');
INSERT INTO DSTRUONG VALUE(N'79762423',N'TH Đào Sơn Tây',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'61 Hiệp Bình');
INSERT INTO DSTRUONG VALUE(N'79762424',N'TH Linh Chiểu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79762427',N'TH Đỗ Tấn Phong',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'103 đường Lê Văn Chí Kp 3');
INSERT INTO DSTRUONG VALUE(N'79762428',N'TH Nguyễn Văn Tây',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'Đường số 4 khu phố 2 P.Bình Chiểu Q.Thủ Đức');
INSERT INTO DSTRUONG VALUE(N'79762429',N'TH Nguyễn Văn Nở',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TDC',N'COLAP',N'PTHONG',N'CBTH',N'Số 12 đường 10 Khu phố 3');
INSERT INTO DSTRUONG VALUE(N'79763401',N'TH Long Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'Khu Tái Định Cư Phước Thiện Phường Long Bình Q9');
INSERT INTO DSTRUONG VALUE(N'79763402',N'TH Phước Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'Đường 18');
INSERT INTO DSTRUONG VALUE(N'79763403',N'TH Tạ Uyên',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'Khu tái định cư Long Sơn');
INSERT INTO DSTRUONG VALUE(N'79763404',N'TH Đinh Tiên Hoàng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'Lê LợiKp2 P.Hiệp PhúQ9');
INSERT INTO DSTRUONG VALUE(N'79763405',N'TH Phú Hữu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'Kp4 Đường 898 P.phú Hữu Q.9 Tp HCM');
INSERT INTO DSTRUONG VALUE(N'79763406',N'TH Võ Văn Hát',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'Kp5 Đỗ Xuân Hợp Phường Phước Long B Quận 9 TPHCM');
INSERT INTO DSTRUONG VALUE(N'79763407',N'TH Long Thạnh Mỹ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'35 đường 20 Kp1 Phường Long Thạnh Mỹ Quận 9.');
INSERT INTO DSTRUONG VALUE(N'79763408',N'TH Hiệp Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'Kp4 P. Hiệp Phú Q9');
INSERT INTO DSTRUONG VALUE(N'79763409',N'TH Nguyễn Minh Quang',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'284 Hoàng Hữu Nam Giãn Dân');
INSERT INTO DSTRUONG VALUE(N'79763410',N'TH Phước Thạnh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'26 Nguyễn Duy Trinh Phước Lai');
INSERT INTO DSTRUONG VALUE(N'79763411',N'TH Trương Văn Thành',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'Kp3 Lã Xuân Oai');
INSERT INTO DSTRUONG VALUE(N'79763412',N'Tiểu học Phong Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'Khu phố 3Phường Tăng Nhơn Phú B Quận 9');
INSERT INTO DSTRUONG VALUE(N'79763413',N'TH Long Phước',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Long Thuận');
INSERT INTO DSTRUONG VALUE(N'79763414',N'TH Bùi Văn Mới',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'Đường Hồ Bá Phấn Kp4');
INSERT INTO DSTRUONG VALUE(N'79763415',N'TH Trường Thạnh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'Số 1 Đường 3 Kp Phước hiệp');
INSERT INTO DSTRUONG VALUE(N'79763417',N'TH Tân Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'Số 7 Đường 138.Khu phố 2.Phường Tân Phú. Quận 9.TpHCM');
INSERT INTO DSTRUONG VALUE(N'79763419',N'TH Lê Văn Việt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'KP1  Man Thiện');
INSERT INTO DSTRUONG VALUE(N'79763420',N'TH Nguyễn Văn Bá',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',N'Đường 359 Khu Phố 5');
INSERT INTO DSTRUONG VALUE(N'79763421',N'TH Trần Thị Bưởi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79763422',N'TH Phạm Văn Chính',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q09',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79764401',N'TH Nguyễn Thượng Hiền',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'36 Nguyễn Thượng Hiền Phường 1 Quận Gò Vấp');
INSERT INTO DSTRUONG VALUE(N'79764402',N'TH Trần Văn Ơn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'90 Nguyễn Thái Sơn');
INSERT INTO DSTRUONG VALUE(N'79764403',N'Tiểu học Phạm Ngũ Lão',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'Số 5 Phạm Ngũ Lão');
INSERT INTO DSTRUONG VALUE(N'79764404',N'TH Hanh Thông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'5 Lê Lợi');
INSERT INTO DSTRUONG VALUE(N'79764405',N'TH Nguyễn Viết Xuân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'332A Dương Quảng Hàm');
INSERT INTO DSTRUONG VALUE(N'79764407',N'TH Trần Quốc Toản',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'Cơ sở 1: A20 Phan Văn Trị Phường 7 Gò Vấp TPHCM
Cơ sở 2: 18/183 Nguyễn Du Phường 7 Gò Vấp TPHCM');
INSERT INTO DSTRUONG VALUE(N'79764408',N'TH Kim Đồng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'1A Quang Trung phường 10 quận Gò Vấp');
INSERT INTO DSTRUONG VALUE(N'79764409',N'TH Nguyễn Thị Minh Khai',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'31/1c Quang Trung');
INSERT INTO DSTRUONG VALUE(N'79764410',N'TH Chi Lăng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'645/2 Quang Trung');
INSERT INTO DSTRUONG VALUE(N'79764411',N'TH An Hội',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'2 Phạm Văn Chiêu');
INSERT INTO DSTRUONG VALUE(N'79764412',N'TH Lam Sơn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'11/3B Phạm Văn Chiêu');
INSERT INTO DSTRUONG VALUE(N'79764413',N'TH Lê Thị Hồng Gấm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'54/11 Phạm Văn Chiêu');
INSERT INTO DSTRUONG VALUE(N'79764414',N'TH Lương Thế Vinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'Số 02 đường 13');
INSERT INTO DSTRUONG VALUE(N'79764415',N'TH Lê Hoàn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'11/214A Lê Đức Thọ');
INSERT INTO DSTRUONG VALUE(N'79764416',N'TH Phan Chu Trinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'40/25A Thống Nhất');
INSERT INTO DSTRUONG VALUE(N'79764417',N'TH Võ Thị Sáu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'450/19A Lê Đức Thọ');
INSERT INTO DSTRUONG VALUE(N'79764418',N'TH Trần Quang Khải',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'197/2 Nguyễn Văn Lượng P.17 Q.GV Tp.HCM');
INSERT INTO DSTRUONG VALUE(N'79764419',N'TH Hoàng Văn Thụ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'161/807E Nguyễn Oanh');
INSERT INTO DSTRUONG VALUE(N'79764420',N'TH Nhựt Tân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'TTHUC',N'PTHONG',N'CBTH',N'Số 3 đường số 9');
INSERT INTO DSTRUONG VALUE(N'79764421',N'TH Lê Quý Đôn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'237/63 Phạm Văn Chiêu');
INSERT INTO DSTRUONG VALUE(N'79764422',N'TH Việt Mỹ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'TTHUC',N'PTHONG',N'CBTH',N'982/8 đường Quang Trung');
INSERT INTO DSTRUONG VALUE(N'79764423',N'TH Lê Đức Thọ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'688/57/44 Đường Lê Đức Thọ');
INSERT INTO DSTRUONG VALUE(N'79764424',N'TH Lê Văn Thọ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'GVP',N'COLAP',N'PTHONG',N'CBTH',N'1115 Lê Đức Thọ Phường 13 Quận Gò Vấp');
INSERT INTO DSTRUONG VALUE(N'79765401',N'Tiểu học Tô Vĩnh Diện',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'26 Vũ Tùng P1 BT');
INSERT INTO DSTRUONG VALUE(N'79765402',N'TH Lam Sơn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'280 Bùi Hữu Nghĩa');
INSERT INTO DSTRUONG VALUE(N'79765403',N'TH Hà Huy Tập',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'7A Phan Đăng Lưu');
INSERT INTO DSTRUONG VALUE(N'79765404',N'Tiểu học Yên Thế',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'377 Lê Quang Định P.5 Q.Bình Thạnh');
INSERT INTO DSTRUONG VALUE(N'79765405',N'TH Nguyễn Bá Ngọc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'47/55 Nguyễn Văn Đậu');
INSERT INTO DSTRUONG VALUE(N'79765406',N'Tiểu học Bế Văn Đàn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'9/1 B Hoàng Hoa Thám p6 QBT');
INSERT INTO DSTRUONG VALUE(N'79765407',N'TH Phan Văn Trị',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'348 Phan Văn Trị');
INSERT INTO DSTRUONG VALUE(N'79765408',N'TH Bình Hòa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'01 Chu Văn An');
INSERT INTO DSTRUONG VALUE(N'79765409',N'TH Trần Quang Vinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'555 Bùi Đình Túy');
INSERT INTO DSTRUONG VALUE(N'79765410',N'TH Bình Lợi Trung',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'138A Nơ Trang Long');
INSERT INTO DSTRUONG VALUE(N'79765411',N'TH Nguyễn Đình Chiểu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'1B Lê Quang Định');
INSERT INTO DSTRUONG VALUE(N'79765412',N'TH Lê Đình Chinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'241 Điện Biên Phủ');
INSERT INTO DSTRUONG VALUE(N'79765413',N'TH Hồng Hà',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'155A Xô Viết Nghệ Tĩnh');
INSERT INTO DSTRUONG VALUE(N'79765414',N'TH Phù Đổng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'22B Xô Viết Nghệ Tĩnh');
INSERT INTO DSTRUONG VALUE(N'79765415',N'TH Thạnh Mỹ Tây',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'10 Phạm Viết Chánh');
INSERT INTO DSTRUONG VALUE(N'79765416',N'TH Nguyễn Trọng Tuyển',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'Hẻm 294 Xô Viết Nghệ Tĩnh');
INSERT INTO DSTRUONG VALUE(N'79765417',N'TH Cửu Long',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'A 19/12  Ngô Tất Tố');
INSERT INTO DSTRUONG VALUE(N'79765418',N'Trường Tiểu học Đống Đa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'1B Điên Biên Phủ');
INSERT INTO DSTRUONG VALUE(N'79765419',N'TH Chu Văn An',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'Số 2 đường 3 CX Chu Văn An');
INSERT INTO DSTRUONG VALUE(N'79765420',N'TH Tầm Vu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'69/3 Xô Viết Nghệ Tĩnh');
INSERT INTO DSTRUONG VALUE(N'79765421',N'TH Thanh Đa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'Khu 2 Cư Xá Thanh Đa');
INSERT INTO DSTRUONG VALUE(N'79765423',N'TH Bạch Đằng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'72/7 Bạch Đằng P.24');
INSERT INTO DSTRUONG VALUE(N'79765426',N'TH Việt Mỹ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'TTHUC',N'PTHONG',N'CBTH',N'2.2-2.3 Đường 12AB KDC Miếu Nổi');
INSERT INTO DSTRUONG VALUE(N'79765428',N'TH Ngôi Nhà Thông Thái',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'TTHUC',N'PTHONG',N'CBTH',N'195/15 Điện Biên Phủ');
INSERT INTO DSTRUONG VALUE(N'79765429',N'Trường Tiểu học Bình Quới Tây',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTH',N'COLAP',N'PTHONG',N'CBTH',N'376 Bình Quới');
INSERT INTO DSTRUONG VALUE(N'79766401',N'TH Lê Văn Sĩ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'322 Nguyễn Trọng Tuyển');
INSERT INTO DSTRUONG VALUE(N'79766402',N'TH Tân Sơn Nhất',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'62 Thăng Long');
INSERT INTO DSTRUONG VALUE(N'79766403',N'TH Nguyễn Thanh Tuyền',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'19 Bùi Thị Xuân');
INSERT INTO DSTRUONG VALUE(N'79766405',N'TH Bình Giã',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'154/321 Phạm Văn Hai');
INSERT INTO DSTRUONG VALUE(N'79766406',N'TH Hoàng Văn Thụ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'55 Hoàng Việt');
INSERT INTO DSTRUONG VALUE(N'79766407',N'TH Phạm Văn Hai',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'370A Phạm Văn Hai');
INSERT INTO DSTRUONG VALUE(N'79766408',N'TH Bạch Đằng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'7 Cách Mạng Tháng Tám');
INSERT INTO DSTRUONG VALUE(N'79766409',N'TH Chi Lăng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'09 Khai Tríphường 06 Q.Tân Bình TPHCM');
INSERT INTO DSTRUONG VALUE(N'79766410',N'TH Đống Đa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'1 Đất Thánh');
INSERT INTO DSTRUONG VALUE(N'79766411',N'TH Bành Văn Trân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'123 Bành Văn Trân');
INSERT INTO DSTRUONG VALUE(N'79766413',N'Tiểu học Trần Văn Ơn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'54 Duy Tân phường 8 quận tân Bình');
INSERT INTO DSTRUONG VALUE(N'79766415',N'TH Ngọc Hồi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'373/1/145 Lý Thường Kiệt');
INSERT INTO DSTRUONG VALUE(N'79766416',N'TH Phú Thọ Hoà',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'550/2 Âu Cơ');
INSERT INTO DSTRUONG VALUE(N'79766417',N'TH Lê Thị Hồng Gấm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'624/21 Âu Cơ - Phường 10 - Quận Tân Bình');
INSERT INTO DSTRUONG VALUE(N'79766418',N'TH Nguyễn Văn Trỗi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'25/1 Tái Thiết');
INSERT INTO DSTRUONG VALUE(N'79766419',N'TH Lạc Long Quân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'947/12 Lạc Long Quân');
INSERT INTO DSTRUONG VALUE(N'79766420',N'TH Cách Mạng Tháng Tám',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'69 Trường Chinh');
INSERT INTO DSTRUONG VALUE(N'79766421',N'Tiểu học Nguyễn Khuyến',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'74 Trần Mai Ninh');
INSERT INTO DSTRUONG VALUE(N'79766422',N'TH Trần Quốc Tuấn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'19 Cộng Hòa');
INSERT INTO DSTRUONG VALUE(N'79766423',N'Trường tiểu học Trần Quốc Toản',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'114 Đồng Đen');
INSERT INTO DSTRUONG VALUE(N'79766424',N'TH Yên Thế',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'31 Núi Thành');
INSERT INTO DSTRUONG VALUE(N'79766425',N'TH Sơn Cang',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'42/2A Văn Chung');
INSERT INTO DSTRUONG VALUE(N'79766426',N'Tiểu học Tân Trụ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'100 Nguyễn Phúc Chu');
INSERT INTO DSTRUONG VALUE(N'79766432',N'TH Nguyễn Văn Kịp',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'45/33 Trần Thái Tông');
INSERT INTO DSTRUONG VALUE(N'79766434',N'TH TT Lương Thế Vinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'TTHUC',N'PTHONG',N'CBTH',N'481/9 Trường Chinh');
INSERT INTO DSTRUONG VALUE(N'79766435',N'TH Thân Nhân Trung',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',N'83 Nguyễn Đức Thuận');
INSERT INTO DSTRUONG VALUE(N'79766S10',N'TH Phan Huy Ích',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TBI',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79767401',N'TH Đoàn Thị Điểm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'16 Trần Văn Ơn');
INSERT INTO DSTRUONG VALUE(N'79767402',N'Tiểu học Lê Lai',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'150 đường Tây Thạnh');
INSERT INTO DSTRUONG VALUE(N'79767403',N'TH Tô Vĩnh Diện',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'51/8 Đô Đốc Lộc');
INSERT INTO DSTRUONG VALUE(N'79767405',N'TH Lê Văn Tám',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'145 Độc Lập');
INSERT INTO DSTRUONG VALUE(N'79767406',N'TH Phan Chu Trinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'193A Thạch Lam');
INSERT INTO DSTRUONG VALUE(N'79767407',N'TH Duy Tân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'39B Lương Trúc Đàm');
INSERT INTO DSTRUONG VALUE(N'79767408',N'TH Võ Thị Sáu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'343 Nguyễn Sơn Phú Thạnh');
INSERT INTO DSTRUONG VALUE(N'79767409',N'TH Hồ Văn Cường',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'51-53 Trịnh Đình Trọng');
INSERT INTO DSTRUONG VALUE(N'79767410',N'TH Huỳnh Văn Chính',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'39 Huỳnh Thiện Lộc');
INSERT INTO DSTRUONG VALUE(N'79767411',N'TH Âu Cơ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'23/15 Trần Văn Cẩn');
INSERT INTO DSTRUONG VALUE(N'79767413',N'TH Tân Hương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'167/29 Tân Quý P Tân Quý');
INSERT INTO DSTRUONG VALUE(N'79767416',N'TH Tân Sơn Nhì',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'905/4 Âu Cơ P.Tân Sơn Nhì');
INSERT INTO DSTRUONG VALUE(N'79767417',N'TH Hiệp Tân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'252/16 Phan Anh');
INSERT INTO DSTRUONG VALUE(N'79767418',N'THCS Hồng Ngọc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'TTHUC',N'PTHONG',N'CBTH',N'58/4 Lũy Bán Bích');
INSERT INTO DSTRUONG VALUE(N'79767419',N'Tiểu học Tân Thới',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'61 Đỗ Thừa Luông');
INSERT INTO DSTRUONG VALUE(N'79767420',N'TH Tân Hóa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'58/29 Lũy Bán Bích Phường Tân Thới Hòa Quận Tân Phú');
INSERT INTO DSTRUONG VALUE(N'79767421',N'TH Đinh Bộ Lĩnh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'91B Bờ Bao Tân Thắng P. Sơn Kỳ Q. Tân Phú');
INSERT INTO DSTRUONG VALUE(N'79767422',N'TH Lê Thánh Tông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'TPH',N'COLAP',N'PTHONG',N'CBTH',N'197199 Đường Trịnh Đình Trọng Phường Phú TRung Quận Tân Phú TP.HCM');
INSERT INTO DSTRUONG VALUE(N'79768401',N'Tiểu học Sông Lô',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'PNH',N'COLAP',N'PTHONG',N'CBTH',N'413 Phan Xích Long');
INSERT INTO DSTRUONG VALUE(N'79768402',N'Cổ Loa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'PNH',N'COLAP',N'PTHONG',N'CBTH',N'L6A cư xá Nguyễn Đình Chiểu');
INSERT INTO DSTRUONG VALUE(N'79768403',N'Cao Bá Quát',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'PNH',N'COLAP',N'PTHONG',N'CBTH',N'92 Phan Đăng Lưu');
INSERT INTO DSTRUONG VALUE(N'79768404',N'Đông Ba',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'PNH',N'COLAP',N'PTHONG',N'CBTH',N'99 Phan Đăng Lưu');
INSERT INTO DSTRUONG VALUE(N'79768406',N'TH Đặng Văn Ngữ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'PNH',N'COLAP',N'PTHONG',N'CBTH',N'35 Đặng Văn Ngữ');
INSERT INTO DSTRUONG VALUE(N'79768407',N'Vạn Tường',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'PNH',N'COLAP',N'PTHONG',N'CBTH',N'15 Hồ Biểu Chánh');
INSERT INTO DSTRUONG VALUE(N'79768408',N'Nguyễn Đình Chính',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'PNH',N'COLAP',N'PTHONG',N'CBTH',N'93-95 Nguyễn Văn Trỗi');
INSERT INTO DSTRUONG VALUE(N'79768409',N'Chí Linh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'PNH',N'COLAP',N'PTHONG',N'CBTH',N'525/73Huỳnh Văn Bánh');
INSERT INTO DSTRUONG VALUE(N'79768410',N'TH Phạm Ngọc Thạch',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'PNH',N'COLAP',N'PTHONG',N'CBTH',N'175 Đặng Văn Ngữ');
INSERT INTO DSTRUONG VALUE(N'79768411',N'Trung Nhất',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'PNH',N'COLAP',N'PTHONG',N'CBTH',N'243/3 Phan Đình Phùng');
INSERT INTO DSTRUONG VALUE(N'79768412',N'TH Lê Đình Chinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'PNH',N'COLAP',N'PTHONG',N'CBTH',N'73/1 Hoàng Văn Thụ');
INSERT INTO DSTRUONG VALUE(N'79768414',N'Tiểu học Hồ Văn Huê',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'PNH',N'COLAP',N'PTHONG',N'CBTH',N'9 Hoàng Minh Giam');
INSERT INTO DSTRUONG VALUE(N'79769401',N'TH An Khánh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q02',N'COLAP',N'PTHONG',N'CBTH',N'Số 2 Đường 9');
INSERT INTO DSTRUONG VALUE(N'79769403',N'TH An Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q02',N'COLAP',N'PTHONG',N'CBTH',N'Khu Dân Cư Sông Giồng Kp2');
INSERT INTO DSTRUONG VALUE(N'79769404',N'TH Giồng Ông Tố',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q02',N'COLAP',N'PTHONG',N'CBTH',N'159 đường 6 Kp4');
INSERT INTO DSTRUONG VALUE(N'79769405',N'TH Huỳnh Văn Ngỡi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q02',N'COLAP',N'PTHONG',N'CBTH',N'78 Quốc Hương Phường Thảo Điền Quận 2.
722 Nguyễn Đăng Giai Phường Thảo Điền Quận 2');
INSERT INTO DSTRUONG VALUE(N'79769406',N'TH Mỹ Thủy',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q02',N'COLAP',N'PTHONG',N'CBTH',N'24 đường 68 Khu dân cư Cát Lái Phường Cát Lái Quận 2');
INSERT INTO DSTRUONG VALUE(N'79769407',N'TH Nguyễn Văn Trỗi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q02',N'COLAP',N'PTHONG',N'CBTH',N'số 6 đường A4 Kp3');
INSERT INTO DSTRUONG VALUE(N'79769408',N'TH Thạnh Mỹ lợi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q02',N'COLAP',N'PTHONG',N'CBTH',N'668 Nguyễn Thị Định');
INSERT INTO DSTRUONG VALUE(N'79769409',N'TH Nguyễn Hiền',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q02',N'COLAP',N'PTHONG',N'CBTH',N'37 Trần Lựu');
INSERT INTO DSTRUONG VALUE(N'79769410',N'TH Lương Thế Vinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q02',N'COLAP',N'PTHONG',N'CBTH',N'215 Trương Văn Bang');
INSERT INTO DSTRUONG VALUE(N'79769411',N'TH - THCS Tuệ Đức',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q02',N'TTHUC',N'PTHONG',N'CBTH',N'1/5 Bis Lương Định Của');
INSERT INTO DSTRUONG VALUE(N'79769412',N'TH An Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q02',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79769413',N'TH Bình Trưng Đông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q02',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79769514',N'TH Trường Anh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q02',N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79769515',N'QT Ngôi Sao Sài Gòn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q02',N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79770403',N'TH Kỳ Đồng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'24 Kỳ Đồng');
INSERT INTO DSTRUONG VALUE(N'79770404',N'TH Mê Linh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'159 Hai Bà Trưng');
INSERT INTO DSTRUONG VALUE(N'79770406',N'TH Lương Định Của',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'576 Nguyễn Đình Chiểu Phường 4 Quận 3');
INSERT INTO DSTRUONG VALUE(N'79770407',N'TH Nguyễn Sơn Hà',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'55A Cao Thắng');
INSERT INTO DSTRUONG VALUE(N'79770408',N'TH Nguyễn Thái Sơn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'12 Huỳnh Tịnh Của');
INSERT INTO DSTRUONG VALUE(N'79770409',N'TH Nguyễn Thanh Tuyền',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'183 Nam Kỳ Khởi Nghĩa');
INSERT INTO DSTRUONG VALUE(N'79770410',N'TH Nguyễn Thi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'448/12 Lê Văn Sỹ');
INSERT INTO DSTRUONG VALUE(N'79770411',N'TH Nguyễn Thiện Thuật',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'633/36 Điện Biên Phủ');
INSERT INTO DSTRUONG VALUE(N'79770412',N'TH Nguyễn Việt Hồng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'292/9 Cách Mạng Tháng 8');
INSERT INTO DSTRUONG VALUE(N'79770413',N'TH Phan Đình Phùng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'491/7 Nguyễn Đinh Chiểu');
INSERT INTO DSTRUONG VALUE(N'79770414',N'Tiểu học Phan Văn Hân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'382/26 Nguyễn Thị Minh Khai');
INSERT INTO DSTRUONG VALUE(N'79770417',N'TH Trần Quang Diệu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'388 Lê Văn Sỹ');
INSERT INTO DSTRUONG VALUE(N'79770418',N'TH Trần Quốc Thảo',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'6 Võ Văn Tần');
INSERT INTO DSTRUONG VALUE(N'79770419',N'TH Trần Văn Đang',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'205/39/15 Trần Văn Đang');
INSERT INTO DSTRUONG VALUE(N'79770420',N'TH Trương Quyền',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',N'946 Trường Sa P.13 Q.3');
INSERT INTO DSTRUONG VALUE(N'79770422',N'TH Thực hành Đại học Sài Gòn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79770423',N'TH Quốc tế Fosco',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q03',NULL,N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79771401',N'TH Hồ Thị Kỷ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'105 Hồ Thị Kỷ');
INSERT INTO DSTRUONG VALUE(N'79771402',N'TH Trần Nhân Tôn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'247 Hòa Hảo');
INSERT INTO DSTRUONG VALUE(N'79771403',N'TH Trương Định',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'382 Sư Vạn Hạnh');
INSERT INTO DSTRUONG VALUE(N'79771405',N'TiH Trần Quang Cơ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'438 Ngô Gia Tự');
INSERT INTO DSTRUONG VALUE(N'79771406',N'TH Nguyễn Chí Thanh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'302 Nguyễn Chí Thanh P5 Q10');
INSERT INTO DSTRUONG VALUE(N'79771407',N'TH Dương Minh Châu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'34 Nguyễn Lâm');
INSERT INTO DSTRUONG VALUE(N'79771408',N'TH Nhật Tảo',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'1 Nhật Tảo');
INSERT INTO DSTRUONG VALUE(N'79771409',N'TH Điện Biên',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'594/1 Điện Biên Phủ');
INSERT INTO DSTRUONG VALUE(N'79771410',N'TH Thiên Hộ Dương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'157 Tô Hiến Thành');
INSERT INTO DSTRUONG VALUE(N'79771411',N'TH Triệu Thị Trinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'91/8D Hòa Hưng');
INSERT INTO DSTRUONG VALUE(N'79771412',N'TH Hoàng Diệu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'283/44-46 CMT8');
INSERT INTO DSTRUONG VALUE(N'79771413',N'TH Lê Thị Riêng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'hẻm 493 Cách Mạng Tháng 8');
INSERT INTO DSTRUONG VALUE(N'79771414',N'TH Lê Đình Chinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'7/4 Thành Thái');
INSERT INTO DSTRUONG VALUE(N'79771415',N'TH Bắc Hải',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'103-105 Bắc Hải Phường 15 Quận 10');
INSERT INTO DSTRUONG VALUE(N'79771416',N'TH Tô Hiến Thành',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'104 Đường Tô Hiến Thành');
INSERT INTO DSTRUONG VALUE(N'79771417',N'TH Võ Trường Toản',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'354/74 Lý Thường Kiệt Phường 14 Quận 10');
INSERT INTO DSTRUONG VALUE(N'79771420',N'TH Trần Văn Kiểu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q10',N'COLAP',N'PTHONG',N'CBTH',N'479 Vĩnh ViễnP7Q10');
INSERT INTO DSTRUONG VALUE(N'79772401',N'TH Hưng Việt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'135 Lạc Long Quân');
INSERT INTO DSTRUONG VALUE(N'79772402',N'TH Nguyễn Thi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'1484 Đường Ba Tháng Hai');
INSERT INTO DSTRUONG VALUE(N'79772403',N'TH Phạm Văn Hai',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'888-890 Nguyễn Chí Thanh');
INSERT INTO DSTRUONG VALUE(N'79772404',N'TH Hòa Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'66 Hòa Bình');
INSERT INTO DSTRUONG VALUE(N'79772405',N'TH Trần Văn Ơn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'612 Lạc Long Quân');
INSERT INTO DSTRUONG VALUE(N'79772406',N'Tiểu học Âu Cơ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'160B Trần Quý');
INSERT INTO DSTRUONG VALUE(N'79772407',N'TH Đề Thám',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'10 Lê Đại Hành');
INSERT INTO DSTRUONG VALUE(N'79772408',N'TH Lạc Long Quân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'225 Lò Siêu');
INSERT INTO DSTRUONG VALUE(N'79772409',N'TH Hàn Hải Nguyên',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'137-139 Thái Phiên');
INSERT INTO DSTRUONG VALUE(N'79772410',N'TH Nguyễn Bá Ngọc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'395/9G Minh Phụng');
INSERT INTO DSTRUONG VALUE(N'79772411',N'TH Thái Phiên',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'393BC Minh Phụng');
INSERT INTO DSTRUONG VALUE(N'79772412',N'TH Phùng Hưng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'250 Lạc Long Quân');
INSERT INTO DSTRUONG VALUE(N'79772413',N'TH Quyết Thắng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'391 Lê Đại Hành P11 Q11');
INSERT INTO DSTRUONG VALUE(N'79772414',N'TH Phú Thọ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'322 Tôn Thất Hiệp');
INSERT INTO DSTRUONG VALUE(N'79772415',N'TH Đại Thành',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'79/22 Âu Cơ');
INSERT INTO DSTRUONG VALUE(N'79772416',N'TH Trưng Trắc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'160 Nguyễn Thị Nhỏ ( nối dài)');
INSERT INTO DSTRUONG VALUE(N'79772417',N'TH Lê Đình Chinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'203 Nguyễn Thị Nhỏ P16 Q11');
INSERT INTO DSTRUONG VALUE(N'79772420',N'TH Việt Mỹ Úc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'TTHUC',N'PTHONG',N'CBTH',N'45 Đường Số 5 Cư Xá Bình Thới');
INSERT INTO DSTRUONG VALUE(N'79772421',N'TH Bình Thới',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'TTHUC',N'PTHONG',N'CBTH',N'181/23-27-29 Bình Thoi');
INSERT INTO DSTRUONG VALUE(N'79772422',N'TH DALAP Việt Mỹ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'TTHUC',N'PTHONG',N'CBTH',N'252 Lạc Long Quân');
INSERT INTO DSTRUONG VALUE(N'79772423',N'Tiểu học Nguyễn Thị Nhỏ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q11',N'COLAP',N'PTHONG',N'CBTH',N'Số 1 đường Nội Bộ C Khu Chung Cư Phú Thọ');
INSERT INTO DSTRUONG VALUE(N'79773401',N'TH Nguyễn Huệ 1',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'COLAP',N'PTHONG',N'CBTH',N'91B Nguyễn Khoái');
INSERT INTO DSTRUONG VALUE(N'79773402',N'TH Đoàn Thị Điểm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'COLAP',N'PTHONG',N'CBTH',N'140 Nguyễn Khoái');
INSERT INTO DSTRUONG VALUE(N'79773403',N'Tiểu học Lê Thánh Tôn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'COLAP',N'PTHONG',N'CBTH',N'209/71 Tôn Thất Thuyết');
INSERT INTO DSTRUONG VALUE(N'79773404',N'TH Vĩnh Hội',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'COLAP',N'PTHONG',N'CBTH',N'183C/3 Tôn Thất Thuyết Phường 4 Quận 4 Thành phố Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79773405',N'TH Đặng Trần Côn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'COLAP',N'PTHONG',N'CBTH',N'202-203 Bến Vân Đồn');
INSERT INTO DSTRUONG VALUE(N'79773406',N'TH Lý Nhơn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'COLAP',N'PTHONG',N'CBTH',N'I28 Bến Vân Đồn');
INSERT INTO DSTRUONG VALUE(N'79773408',N'TH Bạch Đằng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'COLAP',N'PTHONG',N'CBTH',N'57 Lê Quốc Hưng P.12');
INSERT INTO DSTRUONG VALUE(N'79773409',N'Tiểu học Bến Cảng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'COLAP',N'PTHONG',N'CBTH',N'298B Nguyễn Tất Thành');
INSERT INTO DSTRUONG VALUE(N'79773410',N'Tiểu học Xóm Chiếu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'COLAP',N'PTHONG',N'CBTH',N'Số 9 Tôn Đản');
INSERT INTO DSTRUONG VALUE(N'79773411',N'TH Đống Đa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'COLAP',N'PTHONG',N'CBTH',N'177/7 Tôn Thất Thuyết');
INSERT INTO DSTRUONG VALUE(N'79773413',N'TH Đinh Bộ Lĩnh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'COLAP',N'PTHONG',N'CBTH',N'92b/20bis Tôn Thất Thuyết');
INSERT INTO DSTRUONG VALUE(N'79773414',N'TH Nguyễn Trường Tộ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'COLAP',N'PTHONG',N'CBTH',N'181/17 Xóm Chiếu');
INSERT INTO DSTRUONG VALUE(N'79773415',N'TH Nguyễn Thái Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'COLAP',N'PTHONG',N'CBTH',N'2 Tôn Thất Thuyết');
INSERT INTO DSTRUONG VALUE(N'79773416',N'TH Nguyễn Văn Trỗi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'COLAP',N'PTHONG',N'CBTH',N'02 Vĩnh Khánh');
INSERT INTO DSTRUONG VALUE(N'79773417',N'TH Anh Việt Mỹ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q04',N'TTHUC',N'PTHONG',N'CBTH',N'298A Nguyễn Tất Thành');
INSERT INTO DSTRUONG VALUE(N'79774401',N'TH Hàm Tử',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'750-752 Võ Văn Kiệt');
INSERT INTO DSTRUONG VALUE(N'79774402',N'TH Trần Bình Trọng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'120 Trần Bình Trọng');
INSERT INTO DSTRUONG VALUE(N'79774403',N'TH Huỳnh Mẫn Đạt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'5 Huỳnh Mẫn Đạt');
INSERT INTO DSTRUONG VALUE(N'79774404',N'TH Bàu Sen',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'106 Nguyễn Trãi');
INSERT INTO DSTRUONG VALUE(N'79774405',N'Tiểu học Lê Văn Tám',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'144 Trần Phú');
INSERT INTO DSTRUONG VALUE(N'79774406',N'TH Chương Dương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'91-93 Nghĩa Thục');
INSERT INTO DSTRUONG VALUE(N'79774407',N'TH Huỳnh Kiến Hoa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'16 - 18 Nguyễn Văn Đừng');
INSERT INTO DSTRUONG VALUE(N'79774408',N'Tiểu học Phạm Hồng Thái',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'38 Nguyễn Duy Dương');
INSERT INTO DSTRUONG VALUE(N'79774409',N'TH Trần Quốc Toản',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'292 Trần Phú');
INSERT INTO DSTRUONG VALUE(N'79774410',N'Tiểu Học Lý Cảnh Hớn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'02  Xóm Chỉ');
INSERT INTO DSTRUONG VALUE(N'79774411',N'TH Chính Nghĩa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'676 Nguyễn Trãi');
INSERT INTO DSTRUONG VALUE(N'79774412',N'TH Minh Đạo',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'15 Ký Hòa');
INSERT INTO DSTRUONG VALUE(N'79774413',N'TH Nguyễn Viết Xuân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'768 Nguyễn Trãi');
INSERT INTO DSTRUONG VALUE(N'79774414',N'TH Lê Đình Chinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'8-15 Vạn Tượng');
INSERT INTO DSTRUONG VALUE(N'79774415',N'TH Nguyễn Đức Cảnh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'25 Học Lạc');
INSERT INTO DSTRUONG VALUE(N'79774416',N'Tiểu học Hùng Vương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'COLAP',N'PTHONG',N'CBTH',N'266 Hồng Bàng');
INSERT INTO DSTRUONG VALUE(N'79774424',N'THTHCS THPT Văn Lang',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q05',N'TTHUC',N'PTHONG',N'CBTH',N'12 Thuận Kiều');
INSERT INTO DSTRUONG VALUE(N'79775401',N'TH Phạm Văn Chí',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'634 Phạm Văn Chí');
INSERT INTO DSTRUONG VALUE(N'79775402',N'TH Trương Công Định',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'205/42/2 Tân Hòa Đông');
INSERT INTO DSTRUONG VALUE(N'79775403',N'TH Phú Định',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'15 Lý Chiêu Hoàng');
INSERT INTO DSTRUONG VALUE(N'79775404',N'TH Kim Đồng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'1526 Võ Văn Kiệt');
INSERT INTO DSTRUONG VALUE(N'79775405',N'TH Phù Đổng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'Số 2 đường số 9 P11 Q6');
INSERT INTO DSTRUONG VALUE(N'79775406',N'TH Nguyễn Huệ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'178 Gia Phú Phường 1 Quận 6');
INSERT INTO DSTRUONG VALUE(N'79775407',N'TH Him Lam',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'63 Đường Số 11 Cư Xá Đài Rađa');
INSERT INTO DSTRUONG VALUE(N'79775408',N'TH Chi Lăng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'199/31 Lê Quang Sung');
INSERT INTO DSTRUONG VALUE(N'79775409',N'TH Phú Lâm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'Số 6 Tân Hòa Đông');
INSERT INTO DSTRUONG VALUE(N'79775410',N'Tiểu học CHÂU VĂN LIÊM',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'157 Phan Văn Khỏe');
INSERT INTO DSTRUONG VALUE(N'79775411',N'TH Lam Sơn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'820/25 Hậu Giang');
INSERT INTO DSTRUONG VALUE(N'79775412',N'TH Lê Văn Tám',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'30/4 Nguyễn Đình Chi');
INSERT INTO DSTRUONG VALUE(N'79775413',N'TH Nhật Tảo',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'206 Phạm Văn Chí');
INSERT INTO DSTRUONG VALUE(N'79775414',N'TH Võ Văn Tần',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'97 Phạm Đình Hổ');
INSERT INTO DSTRUONG VALUE(N'79775415',N'TH Nguyễn Thiện Thuật',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'100 Phan Văn Khỏe');
INSERT INTO DSTRUONG VALUE(N'79775416',N'TH Bình Tiên',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'260 264 Phan Văn Khỏe');
INSERT INTO DSTRUONG VALUE(N'79775418',N'TH Vĩnh Xuyên',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'TTHUC',N'PTHONG',N'CBTH',N'63 Chu Văn An');
INSERT INTO DSTRUONG VALUE(N'79775420',N'TH Hùng Vương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'660-662 Phạm Văn Chí');
INSERT INTO DSTRUONG VALUE(N'79775421',N'TH - THCS QT Mỹ Úc(TH)',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'TTHUC',N'PTHONG',N'CBTH',N'62_62A Minh Phung');
INSERT INTO DSTRUONG VALUE(N'79775422',N'TH Nguyễn Văn Luông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'489B/6 Hậu Giang');
INSERT INTO DSTRUONG VALUE(N'79775423',N'TH Đặng Nguyên Cẩn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q06',N'COLAP',N'PTHONG',N'CBTH',N'369 Đặng Nguyên Cẩn');
INSERT INTO DSTRUONG VALUE(N'79776401',N'TH Nguyễn Trực',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'38A Dương Bá Trạc');
INSERT INTO DSTRUONG VALUE(N'79776402',N'TH Rạch Ông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'284 Dương Bá Trạc');
INSERT INTO DSTRUONG VALUE(N'79776403',N'Tiểu học Âu Dương Lân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'79 Âu Dương Lân');
INSERT INTO DSTRUONG VALUE(N'79776404',N'TH Vàm Cỏ Đông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'771-795 Phạm Thế Hiển');
INSERT INTO DSTRUONG VALUE(N'79776405',N'TH Thái Hưng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'785 Tạ Quang Bửu');
INSERT INTO DSTRUONG VALUE(N'79776406',N'TH Bông Sao',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'196 Bùi Minh Trực');
INSERT INTO DSTRUONG VALUE(N'79776407',N'Trường Tiểu học Phan Đăng Lưu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'1755 Phạm Thế Hiển');
INSERT INTO DSTRUONG VALUE(N'79776408',N'TH Bùi Minh Trực',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'2225 Phạm Thế Hiển P6q8');
INSERT INTO DSTRUONG VALUE(N'79776409',N'TH An Phong',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'lố F1khu dân cư Hai Thành');
INSERT INTO DSTRUONG VALUE(N'79776410',N'Tiểu học Trần Danh Lâm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'68 Hưng Phú');
INSERT INTO DSTRUONG VALUE(N'79776411',N'Tiểu học Hưng Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'692 B Hưng Phú');
INSERT INTO DSTRUONG VALUE(N'79776413',N'TH Lý Thái Tổ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'275-307 Bình Đông');
INSERT INTO DSTRUONG VALUE(N'79776414',N'TH Tuy Lý Vương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'381 Tùng Thiện Vương P12 Q8');
INSERT INTO DSTRUONG VALUE(N'79776415',N'TH Trần Nguyên Hãn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'45 Trần Nguyên Hãn');
INSERT INTO DSTRUONG VALUE(N'79776416',N'TH Hồng Đức',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'289A Bình Đông');
INSERT INTO DSTRUONG VALUE(N'79776417',N'TH Nguyễn Nhược Thị',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'2 Nguyễn Nhược Thị');
INSERT INTO DSTRUONG VALUE(N'79776418',N'TH Lưu Hữu Phước',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'145 bis Mễ Cốc P15 Q8');
INSERT INTO DSTRUONG VALUE(N'79776419',N'TH Nguyễn Trung Ngạn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'16 đường 3229 Phạm Thế Hiển');
INSERT INTO DSTRUONG VALUE(N'79776420',N'TH Nguyễn Công Trứ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'4 Trương Đình Hội');
INSERT INTO DSTRUONG VALUE(N'79776421',N'TH Lý Nhân Tông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'575 - 577 Hưng Phú');
INSERT INTO DSTRUONG VALUE(N'79776422',N'TH Hoàng Minh Đạo',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'COLAP',N'PTHONG',N'CBTH',N'252 Bông Sao');
INSERT INTO DSTRUONG VALUE(N'79776424',N'TH Đông Nam Á',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79776425',N'TH Khai Nguyên',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q08',N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79777401',N'THCL An Lạc 1',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'687/6 Kinh Dương Vương KP3');
INSERT INTO DSTRUONG VALUE(N'79777402',N'TH An Lạc 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'121 Phùng Tá Chu Kp7');
INSERT INTO DSTRUONG VALUE(N'79777403',N'THCL An Lạc 3',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'504/58C Kinh Dương Vươngphường An Lạc AQuận Bình TânTP.Hồ Chí Minh.');
INSERT INTO DSTRUONG VALUE(N'79777404',N'THCL Bình Hưng Hòa 1',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'15 Hồ Văn Long KP1');
INSERT INTO DSTRUONG VALUE(N'79777405',N'THCL Bình Thuận',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'181 Ấp Chiến Lược Kp3 P. Bình Hưng Hòa A Q. Bình Tân');
INSERT INTO DSTRUONG VALUE(N'79777406',N'TH Bình Trị 1',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'620 Hương Lộ 2 Khu phố 6 Phường Bình Trị Đông Quận Bình Tân');
INSERT INTO DSTRUONG VALUE(N'79777407',N'THCL Tân Tạo',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'119 Hồ Văn Long Kp3 Phường Tân Tạo Bình Tân');
INSERT INTO DSTRUONG VALUE(N'79777408',N'Trường Tiểu học Ngô Quyền',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'118 đường số 3 Kp4');
INSERT INTO DSTRUONG VALUE(N'79777409',N'TH Bình Trị 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'Số 88A đường số 3 phường Bình Trị Đông B');
INSERT INTO DSTRUONG VALUE(N'79777410',N'TH Bình Trị Đông A',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'999 Hương Lộ 2 KP8');
INSERT INTO DSTRUONG VALUE(N'79777411',N'THCL Bình Long',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'Số 1A đường số 4 Kp7 P.Bình Hưng Hòa A Q.Bình Tân');
INSERT INTO DSTRUONG VALUE(N'79777412',N'THCL Lê Công Phép',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'Số 01 Đường Số 1a Khu Phố 6 Phường An Lạc Quận Bình Tân TP Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79777413',N'THCL Bình Trị Đông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'276/68 Tân Hòa Đông Phường Bình Trị Đông Quận Bình Tân');
INSERT INTO DSTRUONG VALUE(N'79777414',N'TH Bình Tân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'1-3 Đường 48 khu phố 9 Phường Tân Tạo Quận Bình Tân');
INSERT INTO DSTRUONG VALUE(N'79777415',N'TH Tân Tạo A',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'Đường Lộ Tẻ Khu phố 3P.Tân Tạo A');
INSERT INTO DSTRUONG VALUE(N'79777416',N'Tiểu học Kim Đồng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'101 Liên khu 4-5 Khu phố 5');
INSERT INTO DSTRUONG VALUE(N'79777417',N'THTT Trí Tuệ Việt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'TTHUC',N'PTHONG',N'CBTH',N'Số 79 đường số 3 KDC Vĩnh Lộc Kp4');
INSERT INTO DSTRUONG VALUE(N'79777419',N'THCL Lê Trọng Tấn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'79/24 Đường số 7 Khu Phố 7 Phường Bình Hưng Hòa Quận Bình Tân TP.HCM');
INSERT INTO DSTRUONG VALUE(N'79777420',N'TH Phù Đổng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'73 Lô Tư P.Bình Hưng Hòa A Q.Bình Tân');
INSERT INTO DSTRUONG VALUE(N'79777422',N'THCL Bình Hưng Hòa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'88/2 Đường số 18 Khu Phố 2 Phường Bình Hưng Hòa Quận Bình Tân TP.HCM');
INSERT INTO DSTRUONG VALUE(N'79777423',N'TH Trần Văn Ơn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'160b Hồ Văn Long');
INSERT INTO DSTRUONG VALUE(N'79777425',N'THCL Lê Quý Đôn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'2A/58 Lê Ngung P. Tân Tạo A Q. Bình Tân TpHCM');
INSERT INTO DSTRUONG VALUE(N'79777426',N'TH Lạc Hồng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BTN',N'COLAP',N'PTHONG',N'CBTH',N'1014/88/11 Đường Tan Kỳ Tân Quý Khu phố 14');
INSERT INTO DSTRUONG VALUE(N'79778401',N'Tiểu học Phan Huy Thực',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'53/12');
INSERT INTO DSTRUONG VALUE(N'79778402',N'TH Lê Quý Đôn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'239/7 Trần Xuân Soạn');
INSERT INTO DSTRUONG VALUE(N'79778403',N'TH Tân Quy',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'217/2 Lê Văn Lương Kp1');
INSERT INTO DSTRUONG VALUE(N'79778404',N'TH Lương Thế Vinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'Số 12 Đường 10 Kp3');
INSERT INTO DSTRUONG VALUE(N'79778405',N'TH Trần Quốc Toản',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'435 Huỳnh Tấn Phát P.Tân Thuận Đông Q7');
INSERT INTO DSTRUONG VALUE(N'79778406',N'TH Tân Thuận',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'8/7 Đường Bùi Văn Ba Khu phố 2');
INSERT INTO DSTRUONG VALUE(N'79778407',N'TH Phù Đổng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'36B Lâm Văn Bền Kp4');
INSERT INTO DSTRUONG VALUE(N'79778408',N'TH Lê Văn Tám',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N's15 Đường Tân Phú P.Tân Phú Q7');
INSERT INTO DSTRUONG VALUE(N'79778409',N'TH Đinh Bộ Lĩnh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'11 đường 53 Nguyễn Thị Thập');
INSERT INTO DSTRUONG VALUE(N'79778410',N'TH Nguyễn Văn Hưởng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'1207 Huỳnh Tấn Phát');
INSERT INTO DSTRUONG VALUE(N'79778411',N'TH Lê Anh Xuân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'23 đường Phú Thuận Kp22');
INSERT INTO DSTRUONG VALUE(N'79778412',N'TH Phú Mỹ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'76/5 Phạm Hữu Lầu');
INSERT INTO DSTRUONG VALUE(N'79778413',N'TiH Nguyễn Thị Định',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'203 Lâm Văn Bền');
INSERT INTO DSTRUONG VALUE(N'79778415',N'TH Kim Đồng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'Nguyễn Văn Linh Kp1');
INSERT INTO DSTRUONG VALUE(N'79778416',N'TH Nam Sài Gòn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'Khu A Đô Thị Mới Nam Sài Gòn');
INSERT INTO DSTRUONG VALUE(N'79778417',N'TH Đặng Thùy Trâm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'215 Trần Xuân Soạn');
INSERT INTO DSTRUONG VALUE(N'79778418',N'TH Võ Thị Sáu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',N'Lô R6 Đặng Đại Độ');
INSERT INTO DSTRUONG VALUE(N'79778419',N'TH Phạm Hữu Lầu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79778420',N'TH Phú Thuận',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'Q07',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79783401',N'TH Tân Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Xóm Đồng');
INSERT INTO DSTRUONG VALUE(N'79783402',N'TH Tân Phú Trung',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Đình');
INSERT INTO DSTRUONG VALUE(N'79783403',N'TH Tân Thông Hội',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Hậu');
INSERT INTO DSTRUONG VALUE(N'79783404',N'TH Tân Tiến',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'61 Trần Tử Bình Ấp Tân Tiến');
INSERT INTO DSTRUONG VALUE(N'79783405',N'TH Lê Thị Pha',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Hậu');
INSERT INTO DSTRUONG VALUE(N'79783406',N'TH Nguyễn Văn Lịch',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Mũi Lớn 2');
INSERT INTO DSTRUONG VALUE(N'79783407',N'TH Liên Minh Công Nông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Bàu Tre 2 Đường Nguyễn Thị Rành');
INSERT INTO DSTRUONG VALUE(N'79783408',N'TH Thị Trấn Củ Chi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Khu phố 1');
INSERT INTO DSTRUONG VALUE(N'79783409',N'TH Tân Thành',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Đường Can Trường khu phố 4 thị trấn Củ Chi');
INSERT INTO DSTRUONG VALUE(N'79783410',N'TH Phước Vĩnh An',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'660 Tỉnh Lộ 8 Ấp 4 xã Phước Vĩnh An Huyện Củ Chi TP HCM');
INSERT INTO DSTRUONG VALUE(N'79783411',N'TH Trần Văn Chẩm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp 5');
INSERT INTO DSTRUONG VALUE(N'79783412',N'TH Phước Hiệp',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Phước Hòa');
INSERT INTO DSTRUONG VALUE(N'79783413',N'TH Phước Thạnh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Số 30 Đường 671 Ấp Chợ');
INSERT INTO DSTRUONG VALUE(N'79783414',N'TH An Phước',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Phước Hưng');
INSERT INTO DSTRUONG VALUE(N'79783415',N'TH Thái Mỹ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Bình Thượng 1');
INSERT INTO DSTRUONG VALUE(N'79783416',N'TH Lê Văn Thế',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Trảng Lắm xã trung lập hạ huyện củ chi');
INSERT INTO DSTRUONG VALUE(N'79783417',N'TH Trung Lập Hạ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Tỉnh lộ 7 Ấp Đồn');
INSERT INTO DSTRUONG VALUE(N'79783419',N'TH Trung Lập Thượng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Số 499 đường Trung Lập ấp Đồng Lớn');
INSERT INTO DSTRUONG VALUE(N'79783420',N'TH An Nhơn Đông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Gò Nổi');
INSERT INTO DSTRUONG VALUE(N'79783421',N'TH An Nhơn Tây',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Xóm Trại xã An Nhơn Tây huyện Củ Chi Tp. Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79783422',N'TH An Phú 1',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp An Hòa');
INSERT INTO DSTRUONG VALUE(N'79783423',N'TH An Phú 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Phú Bình An Phú');
INSERT INTO DSTRUONG VALUE(N'79783424',N'TH Phú Mỹ Hưng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Phú Lợi');
INSERT INTO DSTRUONG VALUE(N'79783425',N'TH Nhuận Đức',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Bàu Chứa');
INSERT INTO DSTRUONG VALUE(N'79783426',N'TH Nhuận Đức 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Ngã Tư');
INSERT INTO DSTRUONG VALUE(N'79783427',N'TH Phạm Văn Cội',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp 3');
INSERT INTO DSTRUONG VALUE(N'79783428',N'TH Phú Hòa Đông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'378A  Ấp Phú Thuận');
INSERT INTO DSTRUONG VALUE(N'79783429',N'TH Phú Hòa Đông 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Xã Phú Hòa Đông Huyện Củ Chi TP Hồ Chí Minh.');
INSERT INTO DSTRUONG VALUE(N'79783430',N'TH Tân Thạnh Tây',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp 2');
INSERT INTO DSTRUONG VALUE(N'79783431',N'TH Trung An',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Đường Võ Thị Hồng Ấp chợ');
INSERT INTO DSTRUONG VALUE(N'79783432',N'TH Hòa Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Đường Bến Than Ấp 1A Xã Hòa Phú - Huyện Củ Chi -TPHCM');
INSERT INTO DSTRUONG VALUE(N'79783433',N'TH Bình Mỹ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp 6B Xã Bình mỹ củ chi TPHCM');
INSERT INTO DSTRUONG VALUE(N'79783434',N'TH Bình Mỹ 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Tỉnh Lộ 9 Ấp 4a');
INSERT INTO DSTRUONG VALUE(N'79783435',N'TH Tân Thạnh Đông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Tỉnh lộ 15 ấp 10');
INSERT INTO DSTRUONG VALUE(N'79783436',N'TH Tân Thạnh Đông 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp 4');
INSERT INTO DSTRUONG VALUE(N'79783437',N'TH Tân Thạnh Đông 3',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'655 Tỉnh lộ 15 Ấp 6');
INSERT INTO DSTRUONG VALUE(N'79783438',N'TH Tân Thông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Chánh xã Tân Thông Hội huyện Củ Chi');
INSERT INTO DSTRUONG VALUE(N'79783439',N'TH Thị Trấn 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'Đường Ninh Tốn Khu phố 2');
INSERT INTO DSTRUONG VALUE(N'79783499',N'TH Nguyễn Thị Lắng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79783600',N'TH-THCS Tân Trung',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CCH',N'COLAP',N'PTHONG',N'CBTH',N'1310 Tỉnh Lộ 8 xã Tân Thạnh Đông Huyện Củ Chi');
INSERT INTO DSTRUONG VALUE(N'79784401',N'TH NGUYỄN AN NINH',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'Số 79 đường Lê Lợi Khu phố 4 Thị Trấn Hóc Mônhuyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784402',N'TH Thới Tam',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'4/111 đường Trần Thị Bốc ấp Nam Thới Xã Thới Tam Thôn huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784403',N'TH Tam Đông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'152/5BĐường Thới Tam Thôn ấp Tam Đông Xã Thới Tam Thôn Huyện Hóc Môn TPHCM');
INSERT INTO DSTRUONG VALUE(N'79784404',N'TH TAM ĐÔNG 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'19/23 đường Thới Tứ 2Ấp Thới Tứ xã Thới Tam Thôn huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784405',N'TH MỸ HUỀ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'59/5A đường Quốc lộ 22 ấp Mỹ Hòa 1 xã Trung Chánh huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784406',N'NAM KỲ KHỞI NGHĨA',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'28/1 đường Hồ Ngọc Cẩn ấp Trung Chánh 1 xã Trung Chánh huyện Hóc Môn.');
INSERT INTO DSTRUONG VALUE(N'79784407',N'TH MỸ HÒA',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'58/8D đường Tân Xuân 6 Ấp Mỹ Hoà 3 xã Tân Xuân huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784408',N'TH ẤP ĐÌNH',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'170 đường Lê Thị Hà Ấp Chánh 1 xã Tân Xuân huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784409',N'TH TÂN HIỆP',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'187đường Lê Lợi Ấp Tân Thới 3 xã Tân Hiệp huyện Hóc Môn Thành phố Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79784410',N'TH Cầu Xáng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'50 đường Liên Xã Tân Hiệp ấp Thới Tây  2 xã Tân Hiệp huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784411',N'TH TÂY BẮC LÂN',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'51/2 đường Nguyễn Thị Huê ấp Hậu Lân xã Bà Điểm huyện Hóc Môn TP.HCM');
INSERT INTO DSTRUONG VALUE(N'79784412',N'TH LÝ CHÍNH THẮNG 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'90/9A Đường Tân Thới Nhì 9 Ấp Thống Nhất 2 Xã Tân Thới Nhì Huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784413',N'TH NHỊ TÂN',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'2/51 đường Dương Công KhiẤp Tân Lập xã Tân Thới Nhì huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784414',N'TH NGÃ BA GIỒNG',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'10 Đường Phan Văn Hớn Ấp 4 xã Xuân Thới Thượng huyện Hóc Môn TP HCM.');
INSERT INTO DSTRUONG VALUE(N'79784415',N'TH HOÀNG HOA THÁM',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'209 đường Đặng Thúc Vịnh Ấp 7 Xã Đông Thạnh huyện Hóc Môn tphcm');
INSERT INTO DSTRUONG VALUE(N'79784416',N'TH THỚI THẠNH',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'363 Đường Đặng Thúc Vịnh ấp 1 xã Đông Thạnh huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784417',N'TH DƯƠNG CÔNG KHI',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'50/43 đường Lê Thị Kim Xuân Thới Sơn ấp 6 xã Xuân Thới Sơn huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784418',N'TH VÕ VĂN THẶNG',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'số 170 đường Bùi Công Trừng ấp 4 xã Nhị Bình huyện Hóc Môn Tp.HCM');
INSERT INTO DSTRUONG VALUE(N'79784419',N'TH BÙI VĂN NGỮ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'1/21 đường Phan Văn Hớn ấp Tiền Lân xã Bà Điểm huyện Hóc Môn.');
INSERT INTO DSTRUONG VALUE(N'79784420',N'TH TRƯƠNG VĂN NGÀI',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'107 đường liên xã Tân Hiệp ấp Tân Thới 2 huyện Hóc Môn Tp.HCM');
INSERT INTO DSTRUONG VALUE(N'79784421',N'TH NHỊ XUÂN',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'8B đường Nguyễn Văn Bứa Ấp 5 xã Xuân Thới Sơn huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784422',N'TH Tân Xuân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'3/6B quốc lộ 22 ấp Mỹ Hòa 4 xã Xuân Thới Đông Huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784423',N'TH XUÂN THỚI THƯỢNG',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'10 đường Phan Văn Hớn Ấp 2 Xã Xuân Thới Thượng Huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784424',N'TH Trần Văn Mười',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'70 đường Trần Văn Mười ấp Xuân Thới Đông 3 xã Xuân Thới Đông huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79784425',N'TH TRẦN VĂN DANH',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'11A đường Đặng Thúc Vịnh Ấp 7 xã Đông Thạnh huyện Hóc Môn.');
INSERT INTO DSTRUONG VALUE(N'79784426',N'NGUYỄN THỊ NUÔI',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'COLAP',N'PTHONG',N'CBTH',N'402 Tô Ký ấp Tam Đông 1 xã Thới Tam Thôn huyện Hóc Môn.');
INSERT INTO DSTRUONG VALUE(N'79784WD5',N'LMG THỎ HỒNG',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'HOM',N'TTHUC',N'PTHONG',N'CBTH',N'4/4C đường Xuân Thới Sơn 31A Ấp 3 xã Xuân Thới Sơn huyện Hóc Môn Tp.HCM');
INSERT INTO DSTRUONG VALUE(N'79785401',N'TH Bình Hưng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'3a Đường Số 10  Kdc Bình Hưng');
INSERT INTO DSTRUONG VALUE(N'79785402',N'TH Võ Văn Vân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp 1 xã Phạm Văn Hai');
INSERT INTO DSTRUONG VALUE(N'79785403',N'TH Phong Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'QL50 Ấp 2xã Phong Phú huyện Bình Chánh');
INSERT INTO DSTRUONG VALUE(N'79785404',N'TH Nguyễn Văn Trân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'E13/414-Đa Phước Bình Chánh TPHCM');
INSERT INTO DSTRUONG VALUE(N'79785405',N'TH Qui Đức',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'A6/12 xã Qui Đức huyện Bình Chánh TpHCM');
INSERT INTO DSTRUONG VALUE(N'79785406',N'TH Hưng Long',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'Đường Đoàn Nguyễn Tuân - C1/30 ấp 3 xã Hưng Long huyện Bình Chánh');
INSERT INTO DSTRUONG VALUE(N'79785407',N'TH Tân Quý Tây',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp 2 xã Tân Quý Tây huyện Bình Chánh TPHCM');
INSERT INTO DSTRUONG VALUE(N'79785408',N'TH Tân Quý Tây 3',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp 2 đường Đoàn Nguyễn Tuân xã Tân Quý Tây huyện Bình Chánh.');
INSERT INTO DSTRUONG VALUE(N'79785409',N'TH Bình Chánh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'c5/42 Trịnh Như Khuê Ấp 3 Bình Chánh xã Bình Chánh Huyện Bình Chánh TPHCM.');
INSERT INTO DSTRUONG VALUE(N'79785410',N'TH An Phú Tây',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp 2 Xã An Phú Tây');
INSERT INTO DSTRUONG VALUE(N'79785411',N'TH Tân Túc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'C1/3G KP3 Thị Trấn Tân Túc Huyện Bình Chánh TP Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79785412',N'TH Tân Kiên',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'Số 2 đường số 2 khu tái định cư ấp 2 xã Tân Kiên');
INSERT INTO DSTRUONG VALUE(N'79785413',N'TH Phạm Văn Hai',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'1A256 Ấp 1 đường Trần Văn Giàu');
INSERT INTO DSTRUONG VALUE(N'79785414',N'TH An Hạ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp 6 xã Phạm Văn Hai huyện Bình Chánh Thành phố HỒ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79785415',N'TH Bình Lợi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'B3/314 Ấp 2 xã Bình Lợi Bình Chánh Tp.HCM');
INSERT INTO DSTRUONG VALUE(N'79785416',N'TH Cầu Xáng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'A3/33 Trần Văn Giàu Ấp 1');
INSERT INTO DSTRUONG VALUE(N'79785417',N'TH Lê Minh Xuân 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'E5/18 Lý Văn Mạnh Kênh B xã Lê Minh Xuân huyện Bình Chánh TPHCM');
INSERT INTO DSTRUONG VALUE(N'79785418',N'Tiểu học Lê Minh Xuân 3',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'Đường Lê Đình Chi ấp 3 xã Lê Minh Xuân huyện Bình Chánh');
INSERT INTO DSTRUONG VALUE(N'79785419',N'TH Tân Nhựt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'A7/178c Ấp 1 Tân Nhựt');
INSERT INTO DSTRUONG VALUE(N'79785420',N'TH Tân Nhựt 6',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'E3/56A');
INSERT INTO DSTRUONG VALUE(N'79785421',N'TH Vĩnh Lộc 1',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'A2/18 ấp 1 xã Vĩnh Lộc A - Huyện Bình Chánh - TP.HCM');
INSERT INTO DSTRUONG VALUE(N'79785422',N'TH Vĩnh Lộc 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'C3/17a Ấp 3');
INSERT INTO DSTRUONG VALUE(N'79785423',N'TH Vĩnh Lộc A',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'F7/32 ẤP 6');
INSERT INTO DSTRUONG VALUE(N'79785424',N'Tiểu học Vĩnh Lộc B',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'42B KDC Vĩnh Lộc Ấp 1 xã Vĩnh Lộc B huyện Bình Chánh Tp.HCM.');
INSERT INTO DSTRUONG VALUE(N'79785427',N'TH Lại Hùng Cường',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp 2xã Vĩnh Lộc B Huyện Bình Chánh TPHCM');
INSERT INTO DSTRUONG VALUE(N'79785428',N'TH Trần Nhân Tôn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'B15/7 ấp 2 xã Bình Chánh huyện Bình Chánh Thành phố Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79785429',N'TH Trần Quốc Toản',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'Ấp 4 xã Vĩnh Lộc B huyện Bình Chánh TP.HCM');
INSERT INTO DSTRUONG VALUE(N'79785430',N'TH Phạm Hùng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'Đường 6A Khu dân cư Đại Phúc ấp 5');
INSERT INTO DSTRUONG VALUE(N'79785431',N'TH Phong Phú 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'Khu Dân Cư Phong Phú 4Xã Phong Phú Huyện Bình Chánh Thành Phố Hồ Chí Minh.');
INSERT INTO DSTRUONG VALUE(N'79785432',N'Trường Tiểu Học An Phú Tây 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',N'đường số 5 khu dân cư An Phú Tây xã An Phú Tây Huyện Bình Chánh. TPHCM');
INSERT INTO DSTRUONG VALUE(N'79785433',N'TH Tân Túc 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79785434',N'TH Huỳnh Văn Bánh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79785435',N'TH Việt Mỹ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'TTHUC',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79785436',N'TH Kim Đồng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79785601',N'TiH - THCS Thế Giới Trẻ Em(TH)',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'BCH',N'TTHUC',N'PTHONG',N'CBTH',N'Số 29 đường số 3 KDC Trung Sơn');
INSERT INTO DSTRUONG VALUE(N'79786401',N'TH Trần Thị Ngọc Hân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'NHB',N'COLAP',N'PTHONG',N'CBTH',N'19 Dương Cát Lợi Khu phố 4 Thị trấn Nhà Bè');
INSERT INTO DSTRUONG VALUE(N'79786402',N'TH Bùi Văn Ba',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'NHB',N'COLAP',N'PTHONG',N'CBTH',N'Số 8 đường số 11 khu dân cư Phước Kiển A Lê Văn Lương ấp 5 xã Phước Kiển huyện Nhà Bè');
INSERT INTO DSTRUONG VALUE(N'79786403',N'Tiểu học Lâm Văn Bền',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'NHB',N'COLAP',N'PTHONG',N'CBTH',N'373 Huỳnh Tấn Phát Khu Phố 7');
INSERT INTO DSTRUONG VALUE(N'79786404',N'TH Nguyễn Trực',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'NHB',N'COLAP',N'PTHONG',N'CBTH',N'1026/3 Ấp 5 Xã Phú Xuân - Huyện Nhà Bè');
INSERT INTO DSTRUONG VALUE(N'79786405',N'TH Nguyễn Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'NHB',N'COLAP',N'PTHONG',N'CBTH',N'247 đường Nguyễn Bình Ấp 2 xã Phú Xuân huyện Nhà Bè');
INSERT INTO DSTRUONG VALUE(N'79786406',N'TH Trang Tấn Khương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'NHB',N'COLAP',N'PTHONG',N'CBTH',N'Ấp 1 xã Long Thới');
INSERT INTO DSTRUONG VALUE(N'79786407',N'TH Dương Văn Lịch',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'NHB',N'COLAP',N'PTHONG',N'CBTH',N'774A Nguyễn Văn Tạo Ấp 1');
INSERT INTO DSTRUONG VALUE(N'79786408',N'TH Nguyễn Văn Tạo',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'NHB',N'COLAP',N'PTHONG',N'CBTH',N'1401 Nguyễn Văn Tạo Ấp 3 Xã Hiệp Phước huyện Nhà Bè Thành phố Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79786409',N'TH Tạ Uyên',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'NHB',N'COLAP',N'PTHONG',N'CBTH',N'782 Lê Văn Lương Ấp 1');
INSERT INTO DSTRUONG VALUE(N'79786410',N'TH Lê Quang Định',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'NHB',N'COLAP',N'PTHONG',N'CBTH',N'218B Lê Văn Lương ấp 3 Phước Kiển Nhà Bè');
INSERT INTO DSTRUONG VALUE(N'79786411',N'Tiểu học Bùi Thanh Khiết',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'NHB',N'COLAP',N'PTHONG',N'CBTH',N'435 đường Đào Sư Tích ấp 3 xã Phước Lộc huyện Nhà Bè');
INSERT INTO DSTRUONG VALUE(N'79786412',N'TH Lê Lợi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'NHB',N'COLAP',N'PTHONG',N'CBTH',N'548/17 hẽm 15 Nguyễn Bình ấp 2');
INSERT INTO DSTRUONG VALUE(N'79786413',N'TH Lê Văn Lương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'NHB',N'COLAP',N'PTHONG',N'CBTH',N'Ấp 4 Nhơn Đức Nhà Bè Tp.HCM');
INSERT INTO DSTRUONG VALUE(N'79786414',N'TH Nguyễn Việt Hồng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'NHB',N'COLAP',N'PTHONG',N'CBTH',NULL);
INSERT INTO DSTRUONG VALUE(N'79787401',N'TH An Nghĩa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'Ấp An Nghĩa Xã An Thới Đông huyện Cần Giờ. TP Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79787402',N'TH An Thới Đông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'Ấp An Hòa Xã An Thới Đông');
INSERT INTO DSTRUONG VALUE(N'79787403',N'TH Doi Lầu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Doi Lầu Xã An Thới Đông huyện Cần Giờ Thành Phố Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79787404',N'TH Bình Khánh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'Đường Rừng Sác Ấp Bình Thuận- xã Bình Khánh');
INSERT INTO DSTRUONG VALUE(N'79787405',N'TH Bình Mỹ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'Đường Trần Quang Đạo ẤP Bình Mỹ Xã Bình Khánh Huyện Cần Giờ');
INSERT INTO DSTRUONG VALUE(N'79787406',N'TH Bình Phước',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Bình An Xã Bình Khánh Huyện Cần Giờ.');
INSERT INTO DSTRUONG VALUE(N'79787407',N'TH Bình Thạnh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'Đường Hà Quang Vóc Ấp Bình Thạnh Xã Bình Khánh Huyện Cần Giờ TP HCM');
INSERT INTO DSTRUONG VALUE(N'79787408',N'TH Cần Thạnh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'Đường Duyên Hải- thị trấn Cần Thạnh');
INSERT INTO DSTRUONG VALUE(N'79787409',N'Tiểu học Đồng Hoà',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Đồng Tranh- xã Đồng Hòa - huyện Cần Giờ');
INSERT INTO DSTRUONG VALUE(N'79787410',N'TH Hoà Hiệp',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Hoà Hiệp- xã Long Hòa');
INSERT INTO DSTRUONG VALUE(N'79787411',N'TH Long Thạnh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'Đường Duyên Hải Ấp Long Thạnh Xã Long Hoà');
INSERT INTO DSTRUONG VALUE(N'79787412',N'Trường Tiểu học Lý Nhơn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'Ấp Tân Điền Lý Nhơn Huyện Cần Giờ Thành Phố Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79787413',N'TH Tam Thôn Hiệp',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'Ấp An Lôc xã Tam Thôn hiệp');
INSERT INTO DSTRUONG VALUE(N'79787414',N'TH Thạnh An',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'159 Ấp Thạnh Bình');
INSERT INTO DSTRUONG VALUE(N'79787415',N'TH Vàm Sát',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',N'Đường Lý Nhơn - Ấp Lý Hòa Hiệp - xã Lý Nhơn - Cần Giờ - Thành phố Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79787416',N'TH Cần Thạnh 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',N'CGI',N'COLAP',N'PTHONG',N'CBTH',NULL);
