INSERT INTO DSTRUONG VALUE(N'79000901',N'TTGDTX Chu Văn An',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'TTGDTX',N'GDTX',N'546 Ngô Gia Tự');
INSERT INTO DSTRUONG VALUE(N'79000902',N'TTGDTX Lê Quý Đôn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'TTGDTX',N'GDTX',N'92 Nguyễn Đình Chiểu');
INSERT INTO DSTRUONG VALUE(N'79000903',N'TTGDTX Tiếng Hoa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'66 Hải Thượng Lãn Ông');
INSERT INTO DSTRUONG VALUE(N'79000905',N'TTGDTX Tôn Đức Thắng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'37/3 - 37/5 Ngô Tất Tố');
INSERT INTO DSTRUONG VALUE(N'79000909',N'Trung tâm Bảo trợ - Dạy nghề và Tạo việc làm Thành phố',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'215 Võ Thị Sáu');
INSERT INTO DSTRUONG VALUE(N'79000911',N'Trung tâm huấn luyện và thi đấu TDTT',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'43 Điện Biên Phủ');
INSERT INTO DSTRUONG VALUE(N'79000912',N'Trung tâm Giáo dục phổ thông Đại học Công nghiệp Thực phẩm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'12 Nguyễn Văn Bảo');
INSERT INTO DSTRUONG VALUE(N'79000914',N'TTGDTX Gia Định',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'TTGDTX',N'GDTX',N'Số 29 đường 13');
INSERT INTO DSTRUONG VALUE(N'79000918',N'TTGDTX Thanh Niên Xung Phong',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'189e Đặng Công Bỉnh Ấp 5');
INSERT INTO DSTRUONG VALUE(N'79000920',N'BTVH Nhạc viện Tp Hồ Chí Minh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'112 Nguyễn Du');
INSERT INTO DSTRUONG VALUE(N'79760901',N'TTGDNN-GTDX Quận 1',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'TTGDTX',N'GDTX',N'16A Nguyễn Thị Minh Khai');
INSERT INTO DSTRUONG VALUE(N'79761901',N'TTGDNN-GDTX Quận 12',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'2 Bis Đường Tô Ký Khu phố 3');
INSERT INTO DSTRUONG VALUE(N'79762901',N'GDNNTX Quận Thủ Đức',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'153/1 Võ Văn Ngân');
INSERT INTO DSTRUONG VALUE(N'79763901',N'TTGDNN-GDTX Quận 9',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'Đường Đình Phong Phú');
INSERT INTO DSTRUONG VALUE(N'79764901',N'GDNNTX Quận Gò Vấp',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'11/3B Phạm Văn Chiêu');
INSERT INTO DSTRUONG VALUE(N'79765901',N'TTGDNN-GDTX Quận Bình Thạnh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'TTGDTX',N'GDTX',N'801/19 Tầm Vu');
INSERT INTO DSTRUONG VALUE(N'79766901',N'TTGDNN-GDTX Quận Tân Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'95/55 TRƯỜNG CHINH PHƯỜNG 12 QUẬN TÂN BÌNH. TP.HỒ CHI MINH.');
INSERT INTO DSTRUONG VALUE(N'79767901',N'TTGDNN-GDTX Quận Tân Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'78/2/45 Phan Đình Phùng');
INSERT INTO DSTRUONG VALUE(N'79768901',N'TTGDNN-GDTX Quận Phú Nhuận',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'GDNNTX',N'GDTX',N'109 Phan Dang Luu');
INSERT INTO DSTRUONG VALUE(N'79769901',N'TTGDNN-GDTX Quận 2',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'45 Phan Bá Vành');
INSERT INTO DSTRUONG VALUE(N'79770901',N'TTGDNN-GDTX Quận 3',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'TTGDTX',N'GDTX',N'204 Lý Chính Thắng');
INSERT INTO DSTRUONG VALUE(N'79771901',N'GDNNTX Quận 10',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'GDNNTX',N'GDTX',N'461-467 Lê Hồng Phong');
INSERT INTO DSTRUONG VALUE(N'79772901',N'TTGDNN-GDTX Quận 11',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'133-135 Nguyễn Chí Thanh (nối dài)');
INSERT INTO DSTRUONG VALUE(N'79773901',N'TTGDNN-GDTX Quận 4',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'GDNNTX',N'GDTX',N'64 - 66 Nguyễn Khoái Phường 2 Quận 4 Tp. Hồ Chí Minh-Cơ sở 1');
INSERT INTO DSTRUONG VALUE(N'79774901',N'TTGDNN-GDTX Quận 5',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'Số 770 Nguyễn Trãi');
INSERT INTO DSTRUONG VALUE(N'79775901',N'TTGDNN-GDTX Quận 6',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'743/15 Hồng Bàng');
INSERT INTO DSTRUONG VALUE(N'79776901',N'TTGDNN-GDTX Quận 8',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'GDNNTX',N'GDTX',N'3-5 Huỳnh Thị Phụng');
INSERT INTO DSTRUONG VALUE(N'79777901',N'TTGDNN-GDTX Quận Bình Tân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'31A Hồ Học Lãm');
INSERT INTO DSTRUONG VALUE(N'79778901',N'TTGDNN-GDTX Quận 7',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'27/3 Khu phố 3 Đường số 10 -P.Bình Thuận -Quận 7');
INSERT INTO DSTRUONG VALUE(N'79783901',N'TTGDNN-GDTX Huyện Củ Chi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'Khu Phố 3 - Thị Trấn Củ Chi - Huyện Củ Chi');
INSERT INTO DSTRUONG VALUE(N'79784901',N'TTGDNN-GDTX Huyện Hóc Môn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'GDNNTX',N'GDTX',N'65 Đỗ Văn Dậy Tân Thới 1 xã Tân Hiệp Huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79785901',N'TTGDNN-GDTX Huyện Bình Chánh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'GDNNTX',N'GDTX',N'A13/9 đường Nguyễn Hữu Trí khu phố 1 thị trấn Tân Túc huyện Bình Chánh tp. Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79786901',N'TTGDNN-GDTX Huyện Nhà Bè',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'5/19 A đường Nguyễn Bình Ấp 1');
INSERT INTO DSTRUONG VALUE(N'79787901',N'TTGDNN-GDTX Huyện Cần Giờ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',NULL,N'GDTX',N'Đường Lương Văn Nho khu phố Giồng Ao thị trấn Cần Thạnh huyện Cần Giờ thành phố Hồ Chí Minh');
