INSERT INTO DSTRUONG VALUE(N'79000702',N'THPT Trưng Vương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'3 Nguyễn Bỉnh Khiêm');
INSERT INTO DSTRUONG VALUE(N'79000703',N'THPT Giồng Ông Tố',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'200/10 Nguyễn Thị Định');
INSERT INTO DSTRUONG VALUE(N'79000704',N'THPT Nguyễn Thị Minh Khai',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'275 Điện Biên Phủ');
INSERT INTO DSTRUONG VALUE(N'79000705',N'THPT Lê Quý Đôn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'110 Nguyễn Thị Minh Khai Phường 6 Quận 3 TP.Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79000706',N'THPT Nguyễn Trãi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'364 Nguyễn Tất Thành');
INSERT INTO DSTRUONG VALUE(N'79000707',N'Phổ thông Năng khiếu thể thao Olympic',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'NKTDTT',N'THPT',N'Đại học Thể dục thể thao TP. Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(NULL,NULL,NULL,NULL,NULL,NULL,N'THPT',N'Khu phố 6 - phường Linh Trung - Quận Thủ Đức - TP. Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79000708',N'THPT Hùng Vương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'124 Hùng Vương');
INSERT INTO DSTRUONG VALUE(N'79000709',N'THPT Mạc Đĩnh Chi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'04 Tân Hòa Đông');
INSERT INTO DSTRUONG VALUE(N'79000710',N'THPT Bình Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'102 Đường Trần Văn Kiểu Phường 1  Quận 6 TPHCM');
INSERT INTO DSTRUONG VALUE(N'79000711',N'THPT Lê Thánh Tôn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'124 đường 17');
INSERT INTO DSTRUONG VALUE(N'79000712',N'THPT Lương Văn Can',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'173 Phạm Hùng');
INSERT INTO DSTRUONG VALUE(N'79000713',N'THPT Ngô Gia Tự',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'360E Bến Bình Đông');
INSERT INTO DSTRUONG VALUE(N'79000714',N'THPT Tạ Quang Bửu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'909 Tạ Quang Bửu');
INSERT INTO DSTRUONG VALUE(N'79000715',N'THPT Nguyễn Huệ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Đường Nguyễn Văn Tăng Kp Châu Phúc Cẩm P.LTM Q9');
INSERT INTO DSTRUONG VALUE(N'79000716',N'THPT Nguyễn Khuyến',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'50 Thành Thái');
INSERT INTO DSTRUONG VALUE(N'79000717',N'THPT Nguyễn Du',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'XX-1 Đồng Nai');
INSERT INTO DSTRUONG VALUE(N'79000718',N'THPT Nguyễn Hiền',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'3 Dương Đình Nghệ-P8-Q11');
INSERT INTO DSTRUONG VALUE(N'79000719',N'THPT Võ Trường Toản',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'482 Đường Nguyễn Thị Đặng - Khu Phố 1');
INSERT INTO DSTRUONG VALUE(N'79000720',N'THPT Thanh Đa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'186 Nguyễn Xí phường 26 quận Bình Thạnh TP.HCM');
INSERT INTO DSTRUONG VALUE(N'79000721',N'THPT Võ Thị Sáu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'95 Đinh Tiên Hoàng');
INSERT INTO DSTRUONG VALUE(N'79000722',N'THPT Gia Định',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'195/29 Xô Viết Nghệ Tĩnh');
INSERT INTO DSTRUONG VALUE(N'79000723',N'THPT Phan Đăng Lưu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'27 Nguyễn Văn Đậu');
INSERT INTO DSTRUONG VALUE(N'79000724',N'THPT Gò Vấp',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'90A Nguyễn Thái Sơn');
INSERT INTO DSTRUONG VALUE(N'79000725',N'THPT Nguyễn Công Trứ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'97 Quang Trung Phường 8 Quận Gò Vấp TP.HCM');
INSERT INTO DSTRUONG VALUE(N'79000726',N'THPT Phú Nhuận',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Số 5 Hoàng Minh Giám');
INSERT INTO DSTRUONG VALUE(N'79000727',N'THPT Tân Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'19 Hoa Bằng');
INSERT INTO DSTRUONG VALUE(N'79000728',N'THPT Nguyễn Chí Thanh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'1A Nguyễn Hiến Lê');
INSERT INTO DSTRUONG VALUE(N'79000729',N'THPT Trần Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'18 Lê Thúc Hoạch');
INSERT INTO DSTRUONG VALUE(N'79000730',N'THPT Nguyễn Thượng Hiền',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'544 Cách Mạng Tháng 8');
INSERT INTO DSTRUONG VALUE(N'79000731',N'THPT Thủ Đức',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'166/24 Đặng Văn Bi');
INSERT INTO DSTRUONG VALUE(N'79000732',N'THPT Nguyễn Hữu Huân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'11 Đoàn Kết');
INSERT INTO DSTRUONG VALUE(N'79000733',N'THPT Tam Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'31 Phú Châu Kp5');
INSERT INTO DSTRUONG VALUE(N'79000734',N'THPT Củ Chi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Tỉnh lộ 8 Khu phố 1');
INSERT INTO DSTRUONG VALUE(N'79000735',N'THPT Quang Trung',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Ấp Phước An');
INSERT INTO DSTRUONG VALUE(N'79000736',N'THPT An Nhơn Tây',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'227Đường Tỉnh lộ 7 Ấp Chợ Cũ Xã An Nhơn Tây Huyện Củ Chi TP.HCM');
INSERT INTO DSTRUONG VALUE(N'79000737',N'THPT Trung Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'1318 tỉnh lộ 8 Ấp 12');
INSERT INTO DSTRUONG VALUE(N'79000738',N'THPT Trung Lập',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'91/3 Trung Lập Ấp Trung Bình.');
INSERT INTO DSTRUONG VALUE(N'79000739',N'THPT Nguyễn Hữu Cầu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'CHUYEN',N'THPT',N'Tô Ký Ấp Mỹ Huề Xã Trung Chánh Huyện Hóc Môn TP. HCM.');
INSERT INTO DSTRUONG VALUE(N'79000740',N'THPT Lý Thường Kiệt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Đường Nam Thới 2 Ấp Nam Thới Xã Thới Tam Thôn');
INSERT INTO DSTRUONG VALUE(N'79000741',N'THPT Bình Chánh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'D17/1D Huỳnh Văn Trí');
INSERT INTO DSTRUONG VALUE(N'79000742',N'THPT Ten Lơ Man',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'8 Trần Hưng Đạo Phường Phạm Ngũ Lão Quận 1 Tp.Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79000743',N'THPT Marie Curie',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'159 Nam Kỳ Khởi Nghĩa');
INSERT INTO DSTRUONG VALUE(N'79000744',N'THPT Trần Khai Nguyên',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'225 Nguyễn Tri Phương');
INSERT INTO DSTRUONG VALUE(N'79000745',N'THPT Nguyễn An Ninh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'93 Trần Nhân Tôn');
INSERT INTO DSTRUONG VALUE(N'79000746',N'THPT Nam Kỳ Khởi Nghĩa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'269/8 Nguyễn Thị Nhỏ');
INSERT INTO DSTRUONG VALUE(N'79000747',N'THPT Nguyễn Thái Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'913-915 Lý Thường Kiệt');
INSERT INTO DSTRUONG VALUE(N'79000748',N'THPT Nguyễn Trung Trực',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'9/168 Lê Đức Thọ');
INSERT INTO DSTRUONG VALUE(N'79000749',N'THPT Hàn Thuyên',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'37 Đặng Văn Ngữ');
INSERT INTO DSTRUONG VALUE(N'79000750',N'THPT Hoàng Hoa Thám',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'6 Hoàng Hoa Thám');
INSERT INTO DSTRUONG VALUE(N'79000751',N'THPT Thăng Long',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'114-116 Hải Thượng Lãn Ông');
INSERT INTO DSTRUONG VALUE(N'79000752',N'THPT Phước Long',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Dương Đình Hội Khu phố 6 - Phường Phước Long B - Q.9');
INSERT INTO DSTRUONG VALUE(N'79000753',N'THPT Bà Điểm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Số7 Nguyễn Thị Sóc Ấp Bắc Lânxã Bà Điểm Huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79000754',N'THPT Tân Phong',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'19F Nguyễn Văn Linh');
INSERT INTO DSTRUONG VALUE(N'79000755',N'THPT Trường Chinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'1 DN11 Khu phố 4');
INSERT INTO DSTRUONG VALUE(N'79000756',N'THPT Phú Hòa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Số 25 đường Huỳnh Thị Bẵng Ấp Phú Lợi');
INSERT INTO DSTRUONG VALUE(N'79000757',N'THPT Tân Thông Hội',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Ấp Bàu Sim');
INSERT INTO DSTRUONG VALUE(N'79000758',N'THPT Tây Thạnh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'27 Đường C2');
INSERT INTO DSTRUONG VALUE(N'79000759',N'THPT Long Trường',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'309 Võ Văn Hát Kp Phước Hiệp phường Long Trường Quận 9 Tp. Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79000760',N'THPT Nguyễn Văn Cừ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'100A ấp 6 xã Xuân Thới Thương Huyện Hóc Môn');
INSERT INTO DSTRUONG VALUE(N'79000761',N'THPT Nguyễn Hữu Tiến',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'9A Ấp 7');
INSERT INTO DSTRUONG VALUE(N'79000762',N'THPT Bình Khánh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Ấp Bình An');
INSERT INTO DSTRUONG VALUE(N'79000763',N'THPT Cần Thạnh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'346 Đường Duyên Hải - Khu Phố Miễu Ba - Thị trấn Cần Thạnh - huyện Cần Giờ');
INSERT INTO DSTRUONG VALUE(N'79000764',N'THPT Trần Hưng Đạo',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'88/955E Lê Đức Thọ');
INSERT INTO DSTRUONG VALUE(N'79000765',N'THPT Hiệp Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Số 63 đường Hiệp Bình khu phố 6');
INSERT INTO DSTRUONG VALUE(N'79000767',N'Tiểu học THCS và THPT Quốc Văn Sài Gòn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'300 Hòa Bình');
INSERT INTO DSTRUONG VALUE(N'79000768',N'THPT Trần Quang Khải',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'343D Lạc Long Quân');
INSERT INTO DSTRUONG VALUE(N'79000769',N'THPT Vĩnh Lộc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'87 Đường Số 3 Kdc Vĩnh Lộc Phường Bình Hưng Hòa B Bình Tân TP.HCM');
INSERT INTO DSTRUONG VALUE(N'79000771',N'THPT Việt Âu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'30/2 Quốc lộ 1A');
INSERT INTO DSTRUONG VALUE(N'79000772',N'THPT Việt Nhật',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'371 Nguyễn Kiệm');
INSERT INTO DSTRUONG VALUE(N'79000773',N'THPT Hưng Đạo',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'103 Nguyễn Văn Đậu');
INSERT INTO DSTRUONG VALUE(N'79000774',N'TH - THCS - THPT Chu Văn An',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'Số 7 Đường Số 1 Khu Phố 1');
INSERT INTO DSTRUONG VALUE(N'79000775',N'Trung học Thực hành Đại học Sư phạm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'280 An Dương Vương Phường 4 Quận 5 Tp. Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79000776',N'Phổ thông Năng Khiếu - ĐHQG Tp. HCM',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'CHUYEN',N'THPT',N'153 Nguyễn Chí Thanh');
INSERT INTO DSTRUONG VALUE(N'79000777',N'THPT Lý Thái Tổ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'1/22/2a Nguyễn Oanh');
INSERT INTO DSTRUONG VALUE(N'79000779',N'THPT Trần Quốc Tuấn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'236/10-12 Thái Phiên');
INSERT INTO DSTRUONG VALUE(N'79000780',N'THPT An Dương Vương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'đường số 3khu phố 6 phường Trường Thọ quận Thủ Đức');
INSERT INTO DSTRUONG VALUE(N'79000781',N'THPT Trần Nhân Tông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'66 Tân Hóa');
INSERT INTO DSTRUONG VALUE(N'79000783',N'THPT Đông Dương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'114/37/12A-E Đường số 10');
INSERT INTO DSTRUONG VALUE(N'79000784',N'THPT Phước Kiển',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Số 1163 Đường Lê Văn Lương Ấp 3');
INSERT INTO DSTRUONG VALUE(N'79000785',N'THPT Nhân Việt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'41-39 Đoàn Hồng Phước');
INSERT INTO DSTRUONG VALUE(N'79000786',N'THPT An Nghĩa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Ấp An Nghĩa');
INSERT INTO DSTRUONG VALUE(N'79000788',N'THPT Phú Lâm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'12-24 đường số 3 chợ Phú Lâm');
INSERT INTO DSTRUONG VALUE(N'79000791',N'Trung học cơ sở và trung học phổ thông Phùng Hưng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'14A Đường số 1 Phường 16 Quận Gò vấp TP Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79000793',N'THPT Nguyễn Hữu Cảnh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'845 Hương Lộ 2');
INSERT INTO DSTRUONG VALUE(N'79000794',N'THPT Nguyễn Văn Linh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Số 02 Đường 3154 Phạm Thế Hiển  Phường 07 Quận 08');
INSERT INTO DSTRUONG VALUE(N'79000795',N'Phân hiệu THPT Lê Thị Hồng Gấm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'147 Pasteur');
INSERT INTO DSTRUONG VALUE(N'79000796',N'THPT Nguyễn Thị Diệu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'12 Trần Quốc Toản');
INSERT INTO DSTRUONG VALUE(N'79000797',N'THPT Quốc Trí',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'313 Nguyễn Văn Luông');
INSERT INTO DSTRUONG VALUE(N'79000798',N'THPT Vĩnh Viễn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'73/7 Lê Trọng Tấn - Phường Sơn Kỳ Quận Tân Phú');
INSERT INTO DSTRUONG VALUE(N'79000799',N'THCS - THPT Trần Cao Vân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'126 Tô Hiệu');
INSERT INTO DSTRUONG VALUE(N'790007A1',N'THPT Bách Việt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'653 Quốc lộ 13 Kp3');
INSERT INTO DSTRUONG VALUE(N'790007A2',N'THPT Việt Mỹ Anh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'252 Lạc Long Quân');
INSERT INTO DSTRUONG VALUE(N'790007A4',N'THCS và THPT Nam Việt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'25 21/1-3 23/7-9 Dương Đức Hiền');
INSERT INTO DSTRUONG VALUE(N'790007A5',N'THPT Văn Lang',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'02-04 Tân Thành');
INSERT INTO DSTRUONG VALUE(N'790007A6',N'THPT Bình Hưng Hòa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'79/19 Đường Số 4 Kp7 P.BHH Q.Bình Tân');
INSERT INTO DSTRUONG VALUE(N'790007A7',N'THPT Bình Tân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'117/4H Hồ Văn Long');
INSERT INTO DSTRUONG VALUE(N'790007A8',N'THPT Nguyễn Tất Thành',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'249C Nguyễn Văn Luông');
INSERT INTO DSTRUONG VALUE(N'790007A9',N'THPT Nguyễn Văn Tăng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Đường số 1 KP Tái Định Cư Long Bửu');
INSERT INTO DSTRUONG VALUE(N'790007B0',N'THPT Trần Văn Giàu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'203/40 Đường Trục Phường 13Quận Bình Thạnh TP.Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'790007B1',N'THPT Phạm Văn Sáng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Ấp 3');
INSERT INTO DSTRUONG VALUE(N'790007B2',N'THPT Đào Sơn Tây',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'53/5 Đường 10 Khu phố 3 Linh Xuân Thủ Đức');
INSERT INTO DSTRUONG VALUE(N'790007B3',N'THPT Tân Túc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'C1/3K Khu Phố 3 Đường Bùi Thanh Khiết Thị Trấn Tân Túc Huyện Bình Chánh');
INSERT INTO DSTRUONG VALUE(N'790007B4',N'THCS và THPT Hai Bà Trưng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'51/4 Nguyễn Thị Nhỏ');
INSERT INTO DSTRUONG VALUE(N'790007B5',N'THPT Thủ Khoa Huân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'481/8 Trường Chinh');
INSERT INTO DSTRUONG VALUE(N'790007B6',N'THPT Vĩnh Lộc B',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Đường số 3 Khu Dân Cư Vĩnh Lộc Bxã VĨnh Lộc B huyện Bình Chánh TPHCM');
INSERT INTO DSTRUONG VALUE(N'790007B7',N'THPT Dương Văn Dương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'39 Đường số 6 KDC Phú Gia Ấp 2');
INSERT INTO DSTRUONG VALUE(N'790007B8',N'THPT Võ Văn Kiệt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'629 Bình Đông');
INSERT INTO DSTRUONG VALUE(N'790007B9',N'Tiểu học THCS và THPT Mùa Xuân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'92 Nguyễn Hữu Cảnh phường 22 Quận Bình Thạnh');
INSERT INTO DSTRUONG VALUE(N'790007C1',N'THPT Năng khiếu TDTT Huyện Bình Chánh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'NKTDTT',N'THPT',N'Ấp 1 Mai Bá Hương xã Lê Minh Xuân huyện Bình Chánh');
INSERT INTO DSTRUONG VALUE(N'790007C2',N'THPT Lê Trọng Tấn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Số 5 Đường D2 Phường Sơn Kỳ Quận Tân Phú');
INSERT INTO DSTRUONG VALUE(N'790007C3',N'THPT Linh Trung',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'790007C4',N'THPT Dương Văn Thì',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'790007C5',N'THPT Bình Chiểu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'790007C6',N'THPT Hồ Thị Bi',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'790007C7',N'THPT Phong Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79000802',N'THPT Thủ Thiêm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'1 Đường Vũ Tông Phan');
INSERT INTO DSTRUONG VALUE(N'79000803',N'THPT Ngô Quyền',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'1360 Huỳnh Tấn Phát');
INSERT INTO DSTRUONG VALUE(N'79000804',N'THPT Thạnh Lộc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'đường Nguyễn Thị Sáu - KP1');
INSERT INTO DSTRUONG VALUE(N'79000805',N'THPT An Lạc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'595 Kinh Dương Vương Phường An Lạc Quận Bình Tân');
INSERT INTO DSTRUONG VALUE(N'79000806',N'THPT Lê Minh Xuân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'G11/1 Ấp 7 Xã Lê Minh Xuân H. Bình Chánh');
INSERT INTO DSTRUONG VALUE(N'79000807',N'THPT Đa Phước',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'D14/410A QL 50 xã Đa Phước -Huyện Bình Chánh TP.HCM');
INSERT INTO DSTRUONG VALUE(N'79000809',N'THCS và THPT Đăng Khoa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'571 Cô Bắc');
INSERT INTO DSTRUONG VALUE(N'79000810',N'THCS và THPT Hồng Hà',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'170 Quang Trung');
INSERT INTO DSTRUONG VALUE(N'79000811',N'TH THCS THPT Tuệ Đức (2)',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'249/108 Tân Thới Nhất 17');
INSERT INTO DSTRUONG VALUE(N'79000812',N'THCS và THPT Nguyễn Bỉnh Khiêm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'140 Lý Chính Thắng');
INSERT INTO DSTRUONG VALUE(N'79000813',N'Tiểu học THCS và THPT Ngô Thời Nhiệm',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'65D Hồ Bá Phấn');
INSERT INTO DSTRUONG VALUE(N'79000814',N'THCSTHPT An Đông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'91 Nguyễn Chí Thanh');
INSERT INTO DSTRUONG VALUE(N'79000815',N'THCS THPT  Ngôi Sao',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'Đường số 18 Khu dân cư An Lạc');
INSERT INTO DSTRUONG VALUE(N'79000816',N'THCS-THPT Phan Bội Châu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79000818',N'TH - THCS - THPT VẠN HẠNH',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'781e Lê Hồng Phong P12 Q10');
INSERT INTO DSTRUONG VALUE(N'79000820',N'THPT Nam Sài Gòn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'Khu A Nam Sài Gòn');
INSERT INTO DSTRUONG VALUE(N'79000822',N'THCS-THPT Hồng Đức',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'Số 8Đường Hồ Đắc DiPhường Tây ThạnhQuận Tân Phú TP Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79000824',N'THCS và THPT Bắc Sơn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'338/24 Nguyễn Văn Quá P. Đông Hưng Thuận Quận 12');
INSERT INTO DSTRUONG VALUE(N'79000825',N'THCS và THPT Phạm Ngũ Lão',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'69/11 Phạm Văn Chiêu P14 Gò Vấp');
INSERT INTO DSTRUONG VALUE(N'79000826',N'THCS và THPT Bạch Đằng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'53/1 Phan Văn Hớn');
INSERT INTO DSTRUONG VALUE(N'79000827',N'THPT Đông Đô',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'12B Nguyễn Hữu Cảnh');
INSERT INTO DSTRUONG VALUE(N'79000828',N'TH THCS và THPT Quốc Tế',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'305 Nguyễn Trọng Tuyển Phường 10 Quận Phú Nhuận');
INSERT INTO DSTRUONG VALUE(N'79000829',N'THCS và THPT  Việt Thanh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'261 Cộng Hòa');
INSERT INTO DSTRUONG VALUE(N'79000830',N'THCS và THPT Trí Đức',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'1333A Thoại Ngọc Hầu');
INSERT INTO DSTRUONG VALUE(N'79000831',N'THCS và THPT Thái Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'10 Trương Hoàng Thanh');
INSERT INTO DSTRUONG VALUE(N'79000832',N'TH-THCS-THPT Thanh Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'192/12 Nguyễn Thái Bình');
INSERT INTO DSTRUONG VALUE(N'79000834',N'THCS và THPT Nhân Văn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'17 Sơn Kỳ');
INSERT INTO DSTRUONG VALUE(N'79000835',N'THCS - THPT Nguyễn Khuyến',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'136 Cộng Hòa');
INSERT INTO DSTRUONG VALUE(N'79000836',N'TH THCS và THPT Trương Vĩnh Ký',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79000838',N'THCS THPT Phan Châu Trinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'Số 12 Đường 23');
INSERT INTO DSTRUONG VALUE(N'79000841',N'THCS - THPT Duy Tân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'106 Nguyễn Giản Thanh');
INSERT INTO DSTRUONG VALUE(N'79000842',N'THPT Nguyễn Hữu Thọ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'2 Bến Vân Đồn');
INSERT INTO DSTRUONG VALUE(N'79000846',N'THCS và THPT Châu Á Thái Bình Dương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'33 C D E Nguyễn Bỉnh Khiêm');
INSERT INTO DSTRUONG VALUE(N'79000848',N'Tiểu học THCS và THPT Việt Mỹ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79000849',N'THCS và THPT Đức Trí',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'39/23 Bùi Văn Ba khu phố 2');
INSERT INTO DSTRUONG VALUE(N'79000850',N'THCS và THPT Đinh Thiện Lý',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'Lô 01 Khu A Nam Sài Gòn');
INSERT INTO DSTRUONG VALUE(N'79000851',N'THCS - THPT Sao Việt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'650q/15 Nguyễn Hữu Thọ');
INSERT INTO DSTRUONG VALUE(N'79000852',N'TH THCS và THPT Nam Mỹ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79000853',N'Trung học thực hành Sài Gòn',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'220 Tần Bình Trọng');
INSERT INTO DSTRUONG VALUE(N'79000854',N'THCS - THPT Lạc Hồng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'2276/5 Quốc lộ 1A');
INSERT INTO DSTRUONG VALUE(N'79000855',N'THCS và THPT Quang Trung Nguyễn Huệ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'223 Nguyễn Tri Phương');
INSERT INTO DSTRUONG VALUE(N'79000856',N'THCS và THPT Khai Minh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'410 Tân Kỳ Tân Quý');
INSERT INTO DSTRUONG VALUE(N'79000857',N'THCS  VÀ THPT NGỌC VIỄN ĐÔNG',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79000858',N'Tiểu học THCS và THPT Tân Phú',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'519 Kênh Tân Hóa');
INSERT INTO DSTRUONG VALUE(N'79000859',N'THCS - THPT Bác Ái',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'187 Gò Cẩm Đệm P.10 Q.Tân Bình TP.HCM');
INSERT INTO DSTRUONG VALUE(N'79000860',N'THCS và THPT Sương Nguyệt Anh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'249 Hòa Hảo');
INSERT INTO DSTRUONG VALUE(N'79000861',N'THCS và THPT Diên Hồng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'11 Thành Thái  phường 14 quận 10');
INSERT INTO DSTRUONG VALUE(N'79000862',N'THPT Minh Đức',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'277 Tân Quý');
INSERT INTO DSTRUONG VALUE(N'79000863',N'THPT Thành Nhân',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'69/12 Nguyễn Cửu Đàm P. Tân Sơn Nhì Q. Tân Phú');
INSERT INTO DSTRUONG VALUE(N'79000865',N'THCS và THPT Hoa Lư',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'201 Phan Văn Hớn');
INSERT INTO DSTRUONG VALUE(N'79000866',N'THCS và THPT Đào Duy Anh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'355 Nguyễn Văn Luông');
INSERT INTO DSTRUONG VALUE(N'79000868',N'THCS và THPT ĐINH TIÊN HOÀNG',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'85 Chế Lan Viên');
INSERT INTO DSTRUONG VALUE(N'79000869',N'THPT Lương Thế Vinh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'131 Cô Bắc');
INSERT INTO DSTRUONG VALUE(N'79000871',N'THPT Năng Khiếu TDTT',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'NKTDTT',N'THPT',N'43 Điện Biên Phủ');
INSERT INTO DSTRUONG VALUE(N'79000872',N'THCS và THPT Việt Anh',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'269A Nguyễn Trọng Tuyển P10 Phú Nhuận');
INSERT INTO DSTRUONG VALUE(N'79000873',N'THCS và THPT Hoa Sen',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'26 Phan Chu Trinh');
INSERT INTO DSTRUONG VALUE(N'79000874',N'Tiểu học THCS và THPT Vinschool',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'Tòa CC3 khu đô thị Vinhomes Central Park 720A Điện Biên Phủ');
INSERT INTO DSTRUONG VALUE(N'79000875',N'THPT Phạm Phú Thứ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'425 - 435 Gia Phú');
INSERT INTO DSTRUONG VALUE(N'79000876',N'THCS và THPT Thạnh An',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79000877',N'TH THCS và THPT Trí Tuệ Việt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79000888',N'Tiểu học THCS và THPT Lê Thánh Tông',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79000C01',N'PTDL Hermann Gmeiner',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'697 Quang Trung');
INSERT INTO DSTRUONG VALUE(N'79000C03',N'Tiểu học THCS và THPT Việt Úc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'594 Ba Tháng Hai - phường 14 - Quận 10 - Tp. HCM');
INSERT INTO DSTRUONG VALUE(N'79000C04',N'THCS Song ngữ Quốc tế Horizon',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'6-6A-8 dường số 44');
INSERT INTO DSTRUONG VALUE(N'79000C05',N'Tiểu học THCS và THPT Quốc tế Canada',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'Số 86 Đường 23');
INSERT INTO DSTRUONG VALUE(N'79000C06',N'TiH - THCS - THPT QUỐC TẾ BẮC MỸ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'1 Đường 5A Kdc Trung Sơn');
INSERT INTO DSTRUONG VALUE(N'79000C07',N'Tiểu học THCS và THPT Thái Bình Dương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'125 Bạch Đằng');
INSERT INTO DSTRUONG VALUE(N'79000C09',N'TH THCS VÀ THPT Nguyễn Tri Phương',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'61a Đường 30');
INSERT INTO DSTRUONG VALUE(N'79000C10',N'Tiểu học THCS và THPT Anh Quốc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79000C11',N'Tiểu học THCS và THPT Emasi Nam Long',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79000C12',N'Tiểu học THCS và THPT Mỹ Việt',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'95 Phan Văn Hớn-Phường Tân Thới Nhất-Quận 12 - Thành Phố Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79000C13',N'Tiểu học THCS và THPT Emasi Vạn Phúc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79000C15',N'Tiểu học THCS và THPT Hoàng Gia',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79000C19',N'Tiểu học THCS và THPT Albert Einstein',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'Khu Dân Cư 13c đại lộ Nguyễn Văn Linh xã Phong Phú huyện Bình Chánh TP Hồ Chí Minh');
INSERT INTO DSTRUONG VALUE(N'79000F01',N'THPT chuyên Lê Hồng Phong',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'CHUYEN',N'THPT',N'235 Nguyễn Văn Cừ');
INSERT INTO DSTRUONG VALUE(N'79000F02',N'THPT chuyên Trần Đại Nghĩa',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'CHUYEN',N'THPT',N'53 Nguyễn Du');
INSERT INTO DSTRUONG VALUE(N'79000F03',N'THPT Chuyên Năng khiếu TDTT Nguyễn Thị Định',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'215 Đường Hoàng Ngân');
INSERT INTO DSTRUONG VALUE(N'7900QT01',N'Tiểu học THCS và THPT Quốc tế Khai Sáng',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'7900QT02',N'Trường Quốc tế Việt Nam - Phần Lan',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'7900QT2',N'Trường Quốc tế Việt Nam - Phần Lan',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79760419',N'Tiểu học THCS  và THPT Quốc tế Á Châu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'Số 41/3-41/4 Bis Trần Nhật Duật');
INSERT INTO DSTRUONG VALUE(N'79767601',N'Tiểu học THCS và THPT Hòa Bình',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'69 Trịnh Đình Thảo');
INSERT INTO DSTRUONG VALUE(N'79770601',N'TiH - THCS - THPT Tây Úc',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'157 Lý Chính Thắng');
INSERT INTO DSTRUONG VALUE(N'79770702',N'Tiểu học THCS và THPT Úc Châu',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',NULL);
INSERT INTO DSTRUONG VALUE(N'79774507',N'THPT Trần Hữu Trang',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'276 Trần Hưng Đạo B');
INSERT INTO DSTRUONG VALUE(N'79777418',N'Tiểu học THCS và THPT Ngôi Sao Nhỏ',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'TTHUC',N'PTHONG',N'THPT',N'10 Đường số 22 Phường Bình Trị Đông B Quận Bình Tân');
INSERT INTO DSTRUONG VALUE(N'79786701',N'THPT Long Thới',N'Sở Giáo dục và Đào tạo Hồ Chí Minh',NULL,N'COLAP',N'PTHONG',N'THPT',N'280 Nguyễn Văn Tạo Ấp 2');
